app/components/ConfirmDeleteModal.tsx, app/test/e2e/images.e2e.ts, app/test/e2e/snapshots.e2e.ts, libs/ui/lib/modal/Modal.tsx, libs/ui/lib/spinner/Spinner.tsx
Closes #1748. This covers all deletes, not just instance create.
=> Add loading state to ok button in confirm delete modal

.eslintrc.json, app/test/e2e/click-everything.e2e.ts, app/test/e2e/disk-create.e2e.ts, app/test/e2e/instance-create.e2e.ts, app/test/e2e/scroll-restore.e2e.ts, app/test/e2e/vpcs.e2e.ts, package-lock.json, package.json
expect-expect and no-useless-await are really handy. It caught a bug where we weren't asserting anything. I think I carried over some muscle memory from testing-library where `getByText` will error if it doesn't match anything. In Playwright, you have to use `expect` explicitly.
=> Upgrade playwright eslint plugin to get new rules

.github/workflows/lintBuildTest.yml, app/test/e2e/image-upload.e2e.ts, playwright.config.ts
We were actually overriding the config with `--workers=2` in the command in the workflow config, but I prefer to centralize that in the config. We now tell it to use `'100%'` of available cores ([which is 2 as of right now](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)).
=> Tweak playwright config

tools/deno/bump-omicron.ts
Now that console is public, we have no reason not to print the list of commits included in a version bump. The result looks like this:
=> Add full commit range to omicron PR body

app/pages/project/instances/instance/tabs/StorageTab.tsx, app/test/e2e/instance/disks.e2e.ts, app/test/e2e/utils.ts
Closes #1771 
Confirmation toast continues to be unimpressive. That will be addressed with #1211.
=> Add snapshot action to instance disks list

app/components/form/SideModalForm.tsx, app/forms/idp/edit.tsx, app/forms/image-edit.tsx, app/forms/image-from-snapshot.tsx, app/test/e2e/snapshots.e2e.ts
Closes #1778
Trivial fix. Turns out we can easily make `submitError` a required prop and prevent this in future. In placeholder forms where we don't have a mutation (image edit and IdP edit) we can just pass null.
=> Show mutation error on snapshot-to-image form

app/components/SystemMetric.tsx, app/components/TimeSeriesChart.tsx, libs/api-mocks/msw/util.ts
Fixes #1640 
There's a few small changes in here.
- We use the largest data point +20% for the graph scale clamping at `maxValue` (if set) which is usually overall capacity
- Rounding the `calculatedMaxValue` to be divisible by 6 so we get even ticks
- Normalizing the mock metrics data to be within max capacity (previously the walker would exceed 100%)
On the `maxValue` rounding – we could do it the other way round where we find a number of ticks that fits but it might be confusing to have it change between graphs. The uneven tick lines was most obvious on disk space because we are using TiB.
=> Scaling utilization Y axis

app/hooks/use-form.ts, app/test/e2e/instance-create.e2e.ts, app/test/e2e/project-create.e2e.ts
Closes #1786 
Closes #1289 because we're not validating on blur anymore
I want to switch to some kind of clever hybrid mode but in the meantime `onSubmit` (which switches to onChange after submit so fixing a field immediately clears the error) is not broken in any way I'm aware of (I'm sure we'll find one), so it wins.
=> Use `useForm` validation `mode: onSubmit` instead of `onTouched`

app/pages/project/images/ImagesPage.tsx, app/pages/system/SiloImagesPage.tsx, app/test/e2e/authz.e2e.ts, app/test/e2e/images.e2e.ts, app/test/e2e/utilization.e2e.ts, app/test/e2e/utils.ts, libs/api-mocks/msw/handlers.ts, libs/api-mocks/msw/util.spec.ts, libs/api-mocks/msw/util.ts, libs/api-mocks/role-assignment.ts, libs/api/roles.ts
Closes #1796 
- Add delete button to silo images
- Remove `onError` on project image delete to fix double toast (delete confirm handles error toast for us)
- Make user role check in mock server more elaborate — let us check for any role on any resource, not just fleet viewer
=> Delete button on silo images table

app/pages/project/instances/actions.tsx, vite.config.ts
I have a messed up instance and all the actions 500. I noticed we don't say anything when these actions error. Now we do.
https://github.com/oxidecomputer/console/assets/3612203/bbd4dfe1-800d-4ba1-b87d-ae5555ba886a
=> Display errors on instance actions

app/layouts/SystemLayout.tsx, app/routes.tsx, app/util/path-builder.spec.ts, app/util/path-builder.ts
I noticed on rack3 that when navigating from sleds list to sled detail (instances tab), there was a delay before the instances table would show up. We were prefetching it, so I figured out it's because the sled detail link goes to `/sleds/abc123`, and then we do a little client-side redirect from there to `/sleds/abc123/instances`, and the loader is on the latter. Strictly speaking I think this might be a bug in React Router, but in the meantime we can fix this either by having the link from the sled list go directly to `/sleds/abc123/instances` or by adding the loader to that redirect route (as I've done here). I vaguely remember there being a problem with this when I tried it before on another page, so I'll leave this up while we mull it over.
=> Fix sled instances prefetch

libs/ui/lib/date-picker/DateRangePicker.tsx
This PR just updates the width of the datetime picker container so it can handle wider values. Although [the original bug report ](https://github.com/oxidecomputer/console/issues/1728) shows the split line when the local datetime uses a leading zero, we'd see this same bug for certain datetimes with "wider" two-digit numbers in locales, as in the screenshots here.
Broken / split:
Fixed / single-line:
=> Update width of time picker to account for wider datetimes

.licenserc.yaml, tools/deno/bump-omicron.ts
Was curious about [dax](https://github.com/dsherret/dax), wanted to try it out. It is cute.
=> Make bump-omicron script cooler with dax, which is zx for deno

libs/api/index.ts
Kinda fun, kinda handy. Uses your session cookie like all other API requests.
=> Stick the api client on `window` 

app/test/e2e/utils.ts
The tests have passed a bunch of times in a row, but flake being flake, that doesn't prove anything. Will revert if we see the flake again.
=> Sleep after closing toast in E2E to reduce flake

app/components/TopBarPicker.tsx
=> Fetch 200 projects for the top bar project picker instead of 20

app/components/EquivalentCliCommand.tsx, app/components/Terminal.tsx, package-lock.json, package.json
Fixes #1840 
Context – many years ago when we cut a new version of the typeface, we (I) thought it might be cute to include the contextual alternate so that "Oxide" or "Ox" would look more brand-like when typed in the console. It's not cute, it's stupid, and that's my cross to bear.
This fixes the issue through an update to the type styles in `@oxide/design-system`. I've also merged in the stylistic sets we're using for the ASCII diagrams on the website, but these don't interfere with regular usage.
=> Turn off contextual alternates in the terminal

app/pages/project/disks/DisksPage.tsx
Fixes #1815.
Adds a toast when snapshotting a disk so the user knows the process has kicked off.
=> Add toast when snapshotting a disk

app/components/form/fields/TextField.tsx, app/forms/silo-create.tsx, app/test/e2e/silos.e2e.ts
Should have gotten in on my last PR, but I thought there'd be more to this form. There are a few more things we should do to polish it (some tooltip descriptions; smarter defaults), but this at least sets it up so users can set quotas when creating a silo.
=> Add quota inputs to silo create form

app/components/form/fields/NumberField.tsx, app/components/form/fields/TextField.tsx
This PR sets up an association by default for the NumberField and TextField components between their \<label>s and \<input>s.
I know you know this; just logging for posterity: Although we already had the association from inputs back to their labels for accessibility, linking them with a `for` (or `htmlFor` for JSX) in the \<label> creates an association in the other direction, meaning clicking on the label will highlight the appropriate input.
Working on getting my .mov → GIF working, but for now, here's a screen recording of the effect:
https://github.com/oxidecomputer/console/assets/22547/dd364154-2a01-4355-98bf-9666eb4e8e3e
=> Add htmlFor to form labels for number and text fields

libs/ui/lib/message/Message.tsx
This came up in conversation with @benjaminleonard earlier and was quick to throw together.
We already have four kinds of Message — 'success' | 'error' | 'notice' | 'info'. Each has a default icon that shows up with it, as seen here:
In a recent mock from @paryhin, we see the possibility of a different icon, to correspond to the message inside the box:
This PR adds a new optional prop to the Message component, allowing for an `alternateIcon`.
The color of the icon is controlled by the `variant` prop, so the only thing that needs to be done here is to pass in one of the existing icon components.
One thing to note is that the Message will happily receive a 16px or 24px icon and will appropriately size it to the Message box, which is good from an ease-of-use standpoint, but might yield …
=> Enable alternate icon on Message component

app/pages/project/instances/instance/tabs/ConnectTab.tsx
Fixes #1870 
We can add the link back in once we have a working doc/guide for Serial Console
=> Remove link to nonexistent Serial Console doc

app/components/TimeAgo.tsx, libs/table/cells/InstanceStatusCell.tsx
Fixes #641 
This PR pulls the formatted "X {seconds|minutes|hours|days|etc.} ago" relative time into a new component that also wraps it in a tooltip that renders the absolute value of that timestamp.
For example:
The description is optional; a relative time without that label still renders the absolute time appropriately:
=> Add a tooltip with absolute datetime to relative time element

libs/table/cells/LinkCell.tsx, libs/ui/lib/table/Table.tsx
Draft because I want to get people's thoughts on it. I think it might be easier to discover and a nicer experience to make the entire link cell clickable. Presently just the text is clickable.
=> Improve clickability of link cells

app/layouts/SystemLayout.tsx, app/routes.tsx, app/util/path-builder.spec.ts, app/util/path-builder.ts
Per [a chat in Matrix](https://matrix.to/#/!rUuGIIGuojsCiHirYz:oxide.computer/$qLz1FvBO5klIv6aLlawB3f75sh8ZKvsLapYTRY4xpQQ?via=oxide.computer&via=unix.house&via=matrix.org), this removes the disabled `Settings` link from the sidebar nav.
Old:
New:
I also removed from the `path-builder.ts` file since we don't see the use of that page for now. Easy to add back in when we need it.
=> Remove 'Settings' link from sidebar nav

libs/api-mocks/msw/handlers.ts, libs/ui/lib/radio/Radio.tsx
Tweaked the disabled radio state to match the other inputs, change cursor, hover no longer changes border colour.
That class is getting pretty complex, but unsure on how we might clean it up. I ended up grouping by state and type.
=> Improve disabled radio state

libs/util/array.spec.tsx, libs/util/array.ts
This solution is pretty ugly internally, but nice thing about it is we don't have to change the calling code because we use `cloneElement` to inject keys.
=> Fix keys warning due to `intersperse`

patches/vite-plugin-html+3.2.2.patch
Working around this issue: https://github.com/vbenjs/vite-plugin-html/issues/58
The plugin [calls `consola.wrap`](https://github.com/vbenjs/vite-plugin-html/blob/a21ec7f4971312cc75ef3d7113b6d86e93dbfeac/packages/core/src/index.ts#L7) at top level, which seems to override `console.log` globally. See https://github.com/unjs/consola
=> Patch `vite-plugin-html` to stop getting the `[log]` prefix on tests

app/pages/SiloUtilizationPage.tsx, app/pages/project/instances/instance/tabs/MetricsTab.tsx, app/pages/system/UtilizationPage.tsx, libs/ui/lib/listbox/Listbox.tsx
Fixes #1905 
Currently, we have some awkward line wrapping when the disk or silo name is too long, as seen here:
This PR adds a few CSS rules to prevent line wrapping for the ListBox select fields.
The full text of the option is still shown within the dropdown itself
This PR also expands the width of the dropdown from `w-48` to `w-80`, but that change isn't strictly necessary, if there's a reason we want to keep the `w-48` width in place. Or we could compromise with `w-64`. I thought it might be an issue where `w-48` works better for a mobile screen with the other elements of the metrics view, but even at `w-48` there are some collisions and overflow issues, so I don't think it's that. Regardless, if we want to leave the width as-is, fine.
=> Tweak CSS to remove awkward line wrapping; widen select box

app/components/ExternalIps.tsx, app/pages/project/disks/DisksPage.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx, libs/table/cells/LinkCell.tsx, libs/ui/lib/date-picker/CalendarCell.tsx, libs/ui/lib/table/Table.tsx, libs/ui/lib/table/table.css, libs/ui/styles/index.css
Follow up from #1886 and feedback from the team.
- Whole row hover state (helps distinguish between rows)
- Link cells are now the same style universally
- Fixed disk cell that was styled differently
I'd would have liked to have the first cell be `text-default` but unsure what to do with the hover state in that instance since we don't have a colour brighter than that.
=> Make links in tables more clearly clickable

app/pages/project/instances/instance/InstancePage.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx
This was the only one I found like that. Eventually we might want a component that's a bit more flexible? The challenge here is that we're using this component inside both tables and the properties table and they appear a little differently.
=> Make `VpcNameFromId` more linkCell-like

app/pages/project/networking/VpcPage/tabs/VpcFirewallRulesTab.tsx, app/test/e2e/firewall-rules.e2e.ts, libs/table/cells/LinkCell.tsx
Followup to #1887. The ambitious version of this involves making the firewall rule edit modal linkable, which in turn requires converting the VpcPage tabs from query param tabs to route tabs. I don't have time to do that right now so I'm doing the minimal version — make a button cell component that has the same styles as the link cell component.
https://github.com/oxidecomputer/console/assets/3612203/96995b8b-7aca-4f52-98c4-4321e86013f0
=> Linkify the firewall rules name cell

libs/ui/lib/field-label/FieldLabel.tsx
Silly silly silly...why is the default browser setting `type="submit"`.
Fixes #1902
=> Fixes tooltip submitting forms on click

app/pages/ProjectsPage.tsx
It just occurred to me how useless and misleading showing the updated time is. The time in question is the last time the project itself was modified, i.e., the name or description changed. That is both a rare occurrence and basically useless information. What you'd really want to know (and what you might think this column means) is when there was last some kind of activity in the project, but we have no way of displaying that. So let's show the created time, which is vaguely useful and unambiguous in meaning.
=> Show project created instead of modified on table

libs/api/hooks.ts
The RQ docs are quite clear that you're not supposed to use rest destructuring on results. They even publish a [lint rule](https://tanstack.com/query/v5/docs/eslint/no-rest-destructuring) to catch it. The irony in our case is that we don't even need the destructure — we're putting the object right back together again and doing a totally unnecessary object copy. The only reason we're doing it is to get TypeScript to recognize that `data` must be non-null after we call `invariant` on it. It will do that narrowing on a freestanding variable, but it doesn't like to do it on an object property. So we have to tell it.
=> Avoid rest destructuring React Query result

app/components/ConfirmActionModal.tsx, app/main.tsx, app/pages/SiloAccessPage.tsx, app/pages/project/access/ProjectAccessPage.tsx, app/pages/project/instances/actions.tsx, app/stores/confirm-action.ts, app/stores/confirm-delete.tsx
Needed to confirm IP pool link/unlink/make default in #1910. We have a really nice way of confirming deletes, but what if we want to confirm an action that's not a delete? Turns out there were only a couple of bits specific to deleting, and I was able to wrap them up in a helper that keeps the API the same.
Existing delete confirmations look and work exactly as they do now:
=> Abstract confirm-delete into more general confirm-action

app/components/form/fields/DiskSizeField.tsx, app/components/form/fields/NumberField.tsx, app/components/form/fields/TextField.tsx, app/forms/instance-create.tsx, app/forms/silo-create.tsx, app/test/e2e/instance-create.e2e.ts
We currently have a few places in the UI where we have TextInputs with `type="number"`. This renders like this:
We have a NumberField component that we're currently using in a few places, but could use in the other places where we currently have `type="number"` … this PR converts those over:
This PR also adds a small bit of logic to translate the `min` and `max` value that we pass in as props to NumberField, converting those to the `minValue` and `maxValue` props that the NumberInput component is expecting. The benefit from that is that we now automatically disable the up/down arrow button in the NumberField component when the input's value is at the boundary number. If the user tries typing in a number beyond the boundary, it gets pulled back to the min/max automatically.
=> Use NumberFields in more places; enhance NumberField component

app/forms/firewall-rules-create.tsx
Closes #1919
It's actually kind of nice to consolidate the submits at the top so you can see the logic side by side.
=> Enter key in firewall rule subforms submits subform

app/test/e2e/instance-create.e2e.ts, libs/api-mocks/msw/db.ts, libs/api-mocks/msw/handlers.ts, libs/api/__tests__/errors.spec.ts, libs/api/__tests__/hooks.spec.tsx, libs/api/errors.ts
We have had multiple people raise the issue that when they tried to create an instance without a default IP pool in their silo, it was almost impossible to figure out what the problem was.
https://github.com/oxidecomputer/omicron/issues/4864
https://github.com/oxidecomputer/omicron/issues/4954
I improved the API error message in https://github.com/oxidecomputer/omicron/pull/4880, but this morning I figured out that in both cases, they were using the web console, and it did not matter what the API error was because we only show `OBJECT NOT FOUND` on instance create when we get a 404 back.
https://github.com/oxidecomputer/console/blob/2aa720d297dd758e83a356a60af6396cacf45b7b/libs/api/errors.ts#L58-L59
So this PR changes that behavior so that the client-side error object we pass around …
=> Display API message on not found errors

libs/util/str.spec.ts
No code changes, so this doesn't need to go into omicron in a hurry. I just wanted to validate the regexes with more kinds of IP addresses.
=> More thorough IP address regex tests

.github/workflows/lintBuildTest.yml, package-lock.json, package.json
It's not nothing! Looks like maybe a 20% improvement. That's cool.
=> Try macos-14 runner for playwright tests

app/forms/ip-pool-range-add.tsx, libs/util/str.spec.ts, libs/util/str.ts
We'll want to access the IP validation in more places, including the Floating IP form. This PR moves the validator @david-crespo added recently to the string utils file for easier access.
=> Move ip validation

app/pages/lookups.ts, app/routes.tsx, app/test/e2e/lookup-routes.e2e.ts
A sneaky idea from @augustuswm, mostly for him to use. Depends on https://github.com/oxidecomputer/omicron/pull/5040, which adds `/lookup/*` as a route in Nexus.
https://github.com/oxidecomputer/console/assets/3612203/23d2fccb-0b19-419c-8bc9-b44bb5794b2a
=> `/lookup/instances/:id` looks up instance and redirects to project instance route

.eslintrc.json, libs/api/client.ts, libs/api/index.ts, libs/api/roles.ts, libs/table/cells/BooleanCell.tsx, libs/table/cells/EnabledCell.tsx, libs/table/cells/FirewallFilterCell.tsx, libs/table/cells/TypeValueListCell.tsx, libs/util/math.spec.ts, libs/util/math.ts
@charliepark ran into a very confusing circular import issue in #1957 due to importing from `'.'`, which made me realize we should just disallow that entirely. The rule worked exactly as I hoped. Here's the output before I fixed the imports:
=> Prevent `import` `from '.'`

app/forms/floating-ip-create.tsx, app/routes.tsx
Didn't occur to me after we put the pool picker under the accordion, but we don't need to prefetch the list of IP pools since the list is hidden. Getting rid of the loader makes the create side modal pop up instantly.
=> Don't prefetch IP pools for floating IP create

app/test/e2e/floating-ip-create.e2e.ts, libs/api-mocks/external-ip.ts, libs/api-mocks/msw/db.ts, libs/api-mocks/msw/handlers.ts
Closes #1966
I considered storing floating and ephemeral IPs in a single `externalIps` table, but it was a bit annoying because the response for the floating IPs list is slightly different from the `ExternalIp` type — it doesn't have a `kind` field because there is only one kind. For some reason it felt better to add the kind in the `instanceExternalIpList` handler than to remove the kind for the `floatingIp` endpoint and friends. We can revisit this in the future if more complex mock functionality makes the two tables feel overcomplicated. Right now nothing ever writes to the ephemeral IPs table, though it probably should — when you create an instance it should add an ephemeral IP.
=> Return floating IPs from mock instance external IPs endpoint

.github/workflows/lintBuildTest.yml
It's using node 20 instead of node 16, which is EOL. Saw warnings [here](https://github.com/oxidecomputer/console/actions/runs/8024401256/attempts/1).
=> Bump actions/cache to v4

app/hooks/use-pagination.ts, app/pages/project/disks/DisksPage.tsx, app/table/QueryTable.tsx, mock-api/disk.ts, test/e2e/disks.e2e.ts, test/e2e/pagination.e2e.ts
The `paginationParams` `useMemo` in `QueryTable` was a bit odd. Note especially that we were ignoring the exhaustive-deps lint check. I think memoizing the callbacks inside of `usePagination` makes it strictly more correct as well as simpler.
=> Better memoization of callbacks in `usePagination`

app/components/AccessNameCell.tsx, app/components/RoleBadgeCell.tsx, app/components/StatusBadge.tsx, app/components/form/fields/DisksTableField.tsx, app/forms/access-util.tsx, app/forms/firewall-rules-create.tsx, app/forms/floating-ip-create.tsx, app/pages/project/instances/instance/SerialConsolePage.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/silos/SiloIdpsTab.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/pages/system/silos/SiloPage.tsx, app/pages/system/silos/SilosPage.tsx, app/table/cells/EnabledCell.tsx, app/table/cells/FirewallFilterCell.tsx, app/table/cells/LabelCell.tsx, app/table/cells/TypeValueCell.tsx, app/ui/index.ts, app/ui/lib/PropertiesTable.tsx, app/ui/lib/Tabs.stories.tsx
Part of #1964 
Wanted to start with a simple migration from the existing Badge component imports over to importing directly from the component file.
=> Remove Badge component from barrel file

app/hooks/use-title.ts, app/layouts/RootLayout.tsx, app/routes.tsx, package-lock.json, package.json, test/e2e/instance/list.e2e.ts, test/e2e/ip-pools.e2e.ts, tsconfig.json
The helpful people of the Remix discord told me how to make this work without every dependency screaming about incompatible peer deps. I'm impressed that everything seems to just work and there are no code changes required. Not sure we need to do this just yet, but there are some [new features](https://react.dev/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024#new-features-in-react-canary) we could take advantage of, as well as possibly bug fixes and performance improvements behind the scenes. 
One immediate downside is that the JS bundle is 12k bigger after gzip, but we should fix that regardless with more aggressive bundle splitting (https://github.com/oxidecomputer/console/issues/2019).
```diff
-dist/assets/app-7ohlR7m-.js     1,077.25 kB │ gzip: 335.16 kB │ map: …
```
=> Try react canary

app/components/form/fields/SshKeysField.tsx
=> Add ssh key on empty state

app/pages/project/vpcs/VpcsPage.tsx
Fixes #2034 
Turns out we only had one location where we … 1) navigate to a new screen for editing (as opposed to loading a form without changing the URL) and 2) didn't already have `apiQueryClient.setQueryData` in place.
With this change, the `Edit VPC` modal loads instantly.
=> pass preloaded data to edit modals

app/pages/project/instances/instance/tabs/MetricsTab.tsx
Fixes #1989 
`Bytes` should be `BYTES`, to match `COUNT`
=> Use proper capitalization in instance metric chart label

tailwind.config.js
It was added [here](https://github.com/oxidecomputer/console/pull/630/files#r801994295) to hide +/- on a number field when we wanted to do that.
=> delete `.appearance-textfield` utility

app/components/form/fields/FileField.tsx, app/components/form/fields/SshKeysField.tsx, app/forms/instance-create.tsx
Fixes #2005 
This PR expands the contexts where we use the `isSubmitting` value to disable form elements.
=> disable form elements when submitting instance create form

.ladle/components.tsx, .ladle/config.mjs
After _The Unbarrelling_ the paths for ladle are not longer correct. This fixes that.
=> Fix broken ladle paths

app/components/EquivalentCliCommand.tsx, app/pages/project/instances/instance/SerialConsolePage.tsx, app/pages/project/instances/instance/tabs/ConnectTab.tsx, app/ui/lib/SettingsGroup.stories.tsx, app/ui/lib/SettingsGroup.tsx, app/util/cli-cmd.ts
Fixes #1991 
I initially tried changing `cta` to take a react component, that way I could just pass the `<EquivalentCliCommand />` component together with the "Connect" button. But I think the issue with that approach is it's very easy to pass the wrong button style or size.
Instead I broke the modal into its own compound that way I could pass a `secondaryCta` prop and just call it directly from that.
=> Add CLI command button to settings group

app/api/hooks.ts, app/pages/project/disks/DisksPage.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/system/networking/IpPoolPage.tsx
Closes #1946
I love this. Using React Query's cache as a go-between, we can do the list prefetch idea with perfect fallback behavior (if the disk is not in the list we fetched, fetch it directly) without having to change the calling code.
I decided to limit each fetch to 200 items, as in general that should cover us. We could easily bump this higher if we wanted — no other code changes are required. In both FF and Chrome on M1 Mac, I timed how long it takes to loop through the items and call `setQueryData` on 200 items and it took 2-4ms. With a possibly more typical 10 items, it takes under 1ms as one would expect.
<details>
<summary>diff showing code changes for testing perf</summary>
```diff
diff --git a/app/pages/project/snapshots/SnapshotsPage.tsx …
```
=> Use list fetches  + `setQueryData` to prefetch items for `*NameFromId` cells

app/components/Sidebar.tsx
A simplification of https://github.com/oxidecomputer/console/pull/2060, which I'll close.
Fixes #2038 
This PR fixes an issue where clicking on the create form of a resource left the sidebar navigation un-highlighted.
Now, if the URL matches the NavLink's `to` property with a `-new` on the end of it (which is our pattern for new resource form URLs), the relevant NavLink will be highlighted. That's a bit cumbersome to describe, but screenshots should help:
If I'm on the Instances page:
and I click on the "New instance" button to go into the form to create a new instance, the NavLink on the side stays highlighted:
This also works for other forms that are contained in sidebars:
=> Highlight NavLink when on create form

tools/deno/api-diff.ts
I wanted to diff two arbitrary commits on omicron main (two releases) and realized the tool only takes a single commit or a PR. Now it can also take two commits.
=> `api-diff` can take two commits

app/pages/settings/ProfilePage.tsx
A quick one; Fixes #2053
This removes the "ID" column from the Groups table on the Profile page, moving it to the standard "Copy ID" button for the table row.
=> Remove id col from Groups table on profile page

app/hooks/use-scroll-restoration.ts
I posted about `useScrollRestoration` on a PR in the react-router repo and someone used it but noticed a bug. This is their fix. Thanks @julamb!
https://github.com/remix-run/react-router/pull/10468#issuecomment-1877312374
=> Floating point fix for scroll restore

app/forms/ip-pool-range-add.tsx, mock-api/ip-pool.ts, test/e2e/ip-pools.e2e.ts
Closes #1963 
Kinda noisy in the validation test because we were using a v6 address as a valid one and I had to change that.
=> IP range add is IPv4 only

app/layouts/RootLayout.tsx, package-lock.json, package.json, tsconfig.json
We just noticed the confirm modal flashes briefly before navigating to instance detail after instance create. We've seen this issue before and fixed it, but it turns out React Canary reintroduces it. We're probably relying on something in React stable that is ultimately a kind of bug, but for now we don't need anything in React Canary, so we can put off figuring it out.
=> Go back to React 18.2.0

app/api/client.ts
The only practical effect this should have is making it less likely that we use cached data on navigation instead of refetching. I think my idea in bumping this up (a long time ago) was that it's cool to be able to rely on the cache if you're navigating back and forth quickly, but I think it's really the opposite — people are probably _trying_ to refresh the data if they're navigating away and back quickly. Related to the problems described in #2095.
The value could go lower because fundamentally we only need this to be big enough to dedupe requests that happen at roughly the same time, but I think 2s is a good starting point.
=> Cut React Query `staleTime` from 10s to 2s

app/components/CapacityBar.tsx
Closes #2081, whatever. We can further break it up later.
Just breaking it up internally for readability, didn't change the external props at all.
I was hoping in #2081 that we'd end up with a set of components that gets composed at the call site, but that might be kind of silly when the layout is so strict and specific. That's why #2085 did it this way too.
After breaking it up I tweaked it very slightly to match what I saw in [Figma](https://www.figma.com/file/GxsrGUQkWwDg6LuiWM9Rft/Capacity-%26-Utilization-v2?type=design&node-id=1636%3A44077&mode=design&t=hlo0iiVTaI667bUl-1):
* icon/title thing's left edge aligns with left edge of bar
* 1rem under bar instead of 3/4
* a tiny bit more space between "provisioned" and the number underneath (not really noticeable)
=> Break up CapacityBar

app/components/form/fields/NameField.spec.tsx, app/components/form/fields/NameField.tsx, test/e2e/project-create.e2e.ts
=> Fix name validation when last character is a capital letter

app/components/form/fields/ImageSelectField.tsx, app/forms/instance-create.tsx, app/util/math.spec.ts, app/util/math.ts, test/e2e/instance-create.e2e.ts
In order to have the form retain the input values into the various tab's forms, I had to update a few fields in the form.
I'll want to take a look at this in the morning, as I suspect there are a few gnarly bits in it.
If this works as I believe it does, though, we'd merge it back into `fix-form-sourceType-bug`, which is, itself, waiting to get merged to `existing-boot-disk`. I was wary enough about the changes here that I didn't want to just Leeroy Jenkins it into `fix-form-sourceType-bug`.
=> Maintain state of fields across tab navigation

.eslintrc.cjs, app/components/form/fields/CheckboxField.tsx, app/components/form/fields/FileField.tsx, app/components/form/fields/ListboxField.tsx, app/components/form/fields/NumberField.tsx, app/components/form/fields/RadioField.tsx, app/components/form/fields/TextField.tsx
TIL `<Controller>` is just `useController` in a trenchcoat. Remove the trenchcoat. Render props are so 2016.
```ts
const Controller = <
TFieldValues extends FieldValues = FieldValues,
TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>(
props: ControllerProps<TFieldValues, TName>,
) => props.render(useController<TFieldValues, TName>(props));
```
https://github.com/react-hook-form/react-hook-form/blob/306627e385738e322cad8dff9e752678f8210020/src/controller.tsx#L46-L51
=> Change all uses of RHF `<Controller>` to `useController`

.gitignore, test/e2e/vpcs.e2e.ts, tools/debug-ci-e2e-fail.sh
Closes #2103 
Works like this. Wish the list was less noisy, but this is bash.
```
$ ./tools/debug-ci-e2e-fail.sh
Attempting to download test failure traces for current branch...
Choose a test trace to view
1) ci-e2e-traces/test-results-chrome/vpcs.e2e.ts-can-nav-to-VpcPage-from--chrome/trace.zip
2) ci-e2e-traces/test-results-chrome/vpcs.e2e.ts-can-nav-to-VpcPage-from--chrome-retry2/trace.zip
3) ci-e2e-traces/test-results-chrome/vpcs.e2e.ts-can-nav-to-VpcPage-from--chrome-retry1/trace.zip
4) ci-e2e-traces/test-results-firefox/vpcs.e2e.ts-can-nav-to-VpcPage-from--firefox/trace.zip
5) ci-e2e-traces/test-results-firefox/vpcs.e2e.ts-can-nav-to-VpcPage-from--firefox-retry2/trace.zip
6) ci-e2e-traces/test-results-firefox/ip-pools.e2e.ts-IP-pool-silo-list-firefox/trace.zip
7) …
```
=> Fix e2e CI failure debug script

app/pages/project/disks/DisksPage.tsx, app/pages/system/networking/IpPoolsTab.tsx, app/table/QueryTable2.tsx, app/table/cells/DefaultCell.tsx, app/table/cells/LinkCell.tsx, app/table/columns/action-col.tsx, mock-api/msw/handlers.ts, test/e2e/disks.e2e.ts, test/e2e/ip-pools.e2e.ts
Closes #2107
Supersedes #2109
In #2109 I had a big outstanding mystery:
> **Unsolved:** why does unmount happen before the loader is complete? Page transition should only happen after loader is done.
To investigate, I tried to reproduce the #2107 problem on StackBlitz with a very minimal setup:
* https://stackblitz.com/edit/vitejs-vite-l4jbyr?file=src%2Fmain.tsx&terminal=dev
* https://stackblitz.com/edit/vitejs-vite-59zkej?file=src%2Fmain.tsx&terminal=dev
But it did not have the issue, so I had to go back to our code and ask myself what we're doing to cause it. The breakthrough came when I replaced the IP pools table with this and the problem went away.
```tsx
<Link to={pb.ipPool({ pool: 'ip-pool-1' })}>ip-pool-1</Link>
<UtilizationCell pool="ip-pool-1" />
```
So most likely it was …
=> Proof of concept: Take column logic out of QueryTable

app/pages/project/disks/DisksPage.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/system/networking/IpPoolsTab.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/table/QueryTable2.tsx, app/table/cells/DefaultCell.tsx, app/table/cells/InstanceLinkCell.tsx, app/table/cells/LinkCell.tsx
These diffs will be a lot nicer to read with whitespace changes hidden.
https://github.com/oxidecomputer/console/pull/2111/files?w=1
=> Convert more tables to `useQueryTable2`

app/pages/ProjectsPage.tsx, app/pages/project/disks/DisksPage.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/project/images/ImagesPage.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcSubnetsTab.tsx, app/pages/project/vpcs/VpcsPage.tsx, app/pages/settings/SSHKeysPage.tsx, app/pages/system/SiloImagesPage.tsx, app/pages/system/inventory/sled/SledInstancesTab.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/networking/IpPoolsTab.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/pages/system/silos/SilosPage.tsx, app/table/QueryTable2.tsx
This is a very noisy but empty change, so we're pulling it out, so the rest of our `useQueryTable` conversions will not be as noisy as #2111.
=> Wrap all the `makeActions` functions in `useCallback`

app/api/hooks.ts, app/forms/image-upload.tsx, app/util/abort.ts, mock-api/msw/handlers.ts
I forgot who suggested this, but it's such a good idea it seems obvious in hindsight. I'm not 100% sure whether we're still seeing the image upload hang from #1469 and #3559 — I think we are, occasionally. Having requests time out after some relatively long amount of time might mitigate the issue entirely.
The first commit here uses a timeout of 5 seconds and simulates a hang of 30 seconds in the mock API handler. With the timeout change commented out, the test fails. With the timeout change in, it passes.
This PR also improves something irrespective of hanging requests: before this PR, when the image upload is canceled, any outstanding chunk POSTs are allowed to finish. Here we pass that abort signal to every request, which means they get canceled immediately when the overall upload is …
=> Timeouts on individual image upload chunk POSTs

app/api/__generated__/http-client.ts, app/api/__tests__/errors.spec.ts, app/api/errors.ts, app/api/hooks.ts
See https://github.com/oxidecomputer/oxide.ts/pull/239
I have another WIP that wants the URL from the response, so instead of adding a URL field to `ApiResult`, I realized I should just include the whole response and stop manually pulling out status and headers.
=> Regen TS client with response on `ApiResult`

app/api/__tests__/errors.spec.ts, app/api/errors.ts, app/api/hooks.ts, app/ui/lib/Toast.tsx, mock-api/msw/util.ts
I have some other work in progress that is more elaborate, but I'm not sure we will be able to make it work. This, however, is definitely fine and should be quite useful for internal debugging at least.
Closes #1945
The key thing is that unlike the network tab, this will log regardless of whether the dev tools are open at request time, so you can open the console after the fact. This will _not_ stick around across refreshes however (unless `Persist logs` is on in the dev tools).
=> Error toasts last 15s instead of 5s, log error info to console

app/components/CapacityBar.tsx, app/forms/silo-create.tsx, mock-api/msw/db.ts, mock-api/msw/handlers.ts, mock-api/msw/util.ts, test/e2e/networking.e2e.ts, test/e2e/silos.e2e.ts, test/e2e/utilization.e2e.ts, test/e2e/utils.ts
Closes #2140 
Also fixes `NaN%` in `CapacityBar` when both numerator and denominator are zero.
=> Convert quotas to GiB before posting

app/forms/floating-ip-create.tsx, test/e2e/floating-ip-create.e2e.ts
=> Remove IP address field from floating IP create form

app/util/math.spec.ts, app/util/math.ts, test/e2e/ip-pools.e2e.ts
This is basically a refactor. It should not change any functionality, though it does add a test we didn't have before.
While discussing changes to date functions in https://github.com/oxidecomputer/console/pull/2153#discussion_r1567920202, I learned that the more natural way to tell the built-in locale-aware functions you want to use whatever the browser's current locale is while also passing some options is to pass `undefined` as the locale instead of `navigator.language` (which should still work but is a bit weirder-feeling). The nice thing about passing undefined is it goes really well with an optional `locale` arg that defaults to `undefined`, and which we only explicitly use in the tests.
=> Use explicit optional locale arg in math functions, rework tests accordingly

app/components/TopBarPicker.tsx, app/forms/project-create.tsx, app/pages/ProjectsPage.tsx, app/util/path-builder.spec.ts, app/util/path-builder.ts
I noticed some janky behavior on nav when I click the project in the top bar. 
https://github.com/oxidecomputer/console/assets/3612203/ee4a45d2-4d0e-4174-b9e1-5a62a531fef3
This was due to that link going to `/projects/my-proj`, which is not actually a real page in its own right: it does a client-side redirect to `/project/my-proj/instances`. In general our approach in cases like this (a parent route with a default child that we always redirect to) is to link directly to the default child.
But I noticed is that path builder is not set up to encourage the right choice. `pb.project()` went to `/projects/my-proj` because it is used in the construction of many other paths, even though we don't actually ever want to link there. So what I did here is pull out a `projectBase` helper function that …
=> Fix empty screen flash before nav on clicking project in top bar

app/components/RefetchIntervalPicker.tsx, app/components/TimeAgo.tsx, app/forms/disk-create.tsx, app/forms/idp/edit.tsx, app/forms/image-edit.tsx, app/pages/project/instances/instance/InstancePage.tsx, app/pages/project/vpcs/VpcPage/VpcPage.tsx, app/pages/system/silos/SiloPage.tsx, app/table/columns/common.tsx, app/ui/lib/DateTime.tsx, app/util/date.spec.ts, app/util/date.ts, test/e2e/dates.e2e.ts, test/e2e/silos.e2e.ts, test/e2e/vpcs.e2e.ts
We're working to tighten up the data tables (vertically), so are moving the date cell from two lines to one line.
Currently, it looks like this:
With this PR, it now looks like this:
On smaller screens, the date wraps:
=> Convert date cell to single line

app/api/hooks.ts, app/components/RefreshButton.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/InstancePage.tsx
Necessary stopgap until we do more polling. I have some followup work that simulates state changes more fancily in the mock server, which will let us test the button in an e2e.
=> Refresh button on instance detail page

app/pages/project/instances/actions.tsx, app/stores/confirm-delete.tsx, test/e2e/instance/list.e2e.ts, test/e2e/network-interface-create.e2e.ts, test/e2e/utils.ts, test/e2e/z-index.e2e.ts
Fixes #2093 
Works for both the instances list view row action and the individual instance page action.
(Open to copy suggestions, etc.)
=> Add confirmation modal to instance stop

app/components/RefreshButton.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/InstancePage.tsx
Closes #1995 
Imagine my delight discovering that `invalidateQueries` returns a promise that completes when the actual query finishes refetching! That makes it extremely easy to turn on a spinner when it starts and turn it off when it ends. How great is that!
https://github.com/oxidecomputer/console/assets/3612203/49481520-22ef-4334-bd15-452c2d9bf7a6
=> Animate refresh button

app/pages/project/instances/InstancesPage.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcFirewallRulesTab.tsx, app/pages/system/UtilizationPage.tsx, app/table/QueryTable.tsx, app/table/Table.tsx, app/ui/lib/Table.tsx
This PR sets the default table row height to the `h-12` height, rather than the larger `h-16`.
So we move from a table looking like this:
To something more compact, like this:
37.5% more data on the screen*!
There are still some tables that require a larger height, and we can pass in a `rowHeight` prop to enable that. Here we have the `InstancesPage` table, which uses the `useQueryTable` hook, which invokes the `app/table/Table.tsx` component. With this wrapper component, we can pass in `rowHeight` as a prop to the overall `Table` component and the component passes it through to the `Table.Cell` in `ui/lib/Table.tsx`.
We also sometimes use the `ui/lib/Table.tsx` file directly, as in the `UtilizationPage` table. In cases like that, we have to pass the `height` prop directly to each …
=> Set table cells to have shorter default height

app/pages/ProjectsPage.tsx, app/pages/SiloAccessPage.tsx, app/pages/project/access/ProjectAccessPage.tsx, app/pages/project/disks/DisksPage.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/project/images/ImagesPage.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcFirewallRulesTab.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcSubnetsTab.tsx, app/pages/project/vpcs/VpcsPage.tsx, app/pages/system/SiloImagesPage.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/networking/IpPoolsPage.tsx, app/pages/system/silos/SiloIdpsTab.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/pages/system/silos/SilosPage.tsx, app/ui/lib/CreateButton.tsx, app/ui/lib/Table.tsx
This PR updates the buttons (and links, where appropriate) that sit just above tables in the UI, adding a plus icon (technically, a _roundel_) to the buttons.
I'm not totally sure that the icon makes sense when paired with the text reading "Promote image", but figured that consistency across the buttons was more important than the semantic quibbling on that one button. That being said, I'm open to input.
=> Add plus icon to all "new" buttons above tables

app/pages/project/vpcs/VpcPage/tabs/VpcSubnetsTab.tsx, app/pages/system/inventory/sled/SledInstancesTab.tsx, app/ui/lib/Table.tsx
Our tables are constructed by dropping a `div` inside each `td` and then putting the contents of the cell into that div. I tried simplifying things by moving the borders to the cells, but it proved to be trickier than I thought it would be, and I wasn't confident that I wouldn't introduce edge case CSS bugs. So I've mostly left it as it was.
One change that I did make was to only apply the height class to the contained `<div>`, rather than to the `<div>` and the `<td>` that wraps it. There was no reason I could find to apply the class to both, as the `<td>` will occupy the proper size based on the child element (the `<div>`). I tried to see if there were any unexpected rendering issues with the class in only one place, but did not find anything. If @benjaminleonard or @david-crespo has …
=> Small table cell refactor

mock-api/msw/handlers.ts, test/e2e/instance.e2e.ts, test/e2e/network-interface-create.e2e.ts, test/e2e/utils.ts, test/e2e/z-index.e2e.ts
Instead of going straight to stopped (or started, or whatever it is) instances stop at an intermediate state (stopping, starting, etc.) immediately and only hit the target state after 1 second. Instance create does `creating (1s) -> starting (4s) -> running`.
I've been meaning to do this for a while. It's neat because it lets us test the refresh button.
https://github.com/oxidecomputer/console/assets/3612203/dd189be5-7586-4e36-86c8-7b66b2fbec97
=> Instance state changes asynchronously in mock API

app/components/CapacityBar.tsx, app/pages/system/networking/IpPoolPage.tsx
Fixes #2178 
This PR just adds some CSS capping the max-width of the capacity bar to 50% of the screen for the IP Pool page.
I tested with spoofed data, and At whatever point IPv6 IPs are in the mix, the left (IPv4) and right (IPv6) side should have equal widths.
=> set max-width of capacity bar to 50%

app/components/ExternalIps.tsx, app/pages/project/instances/instance/InstancePage.tsx, test/e2e/instance-networking.e2e.ts
Fixes #2171 
We currently only allow for a "copy to clipboard" function when there's a single external IP in the list in the header. This PR makes it so that any IP in the list is copyable.
We should add a dropdown, a la ListPlusCell, for when there are more than … 3(? 2?) IPs, but that can be a subsequent PR.
=> make all external IPs in header copyable

app/pages/project/instances/actions.tsx, app/stores/confirm-delete.tsx
=> Add note about disks to instance delete confirm

app/forms/ssh-key-create.tsx, app/pages/settings/SSHKeysPage.tsx, test/e2e/ssh-keys.e2e.ts
Just noticed these were missing.
=> Add success toasts for create and delete SSH key

package-lock.json, package.json
Note that even though package.json says 1.2.10 -> 1.4.4, we were already on 1.4.3 in the lockfile, so this is a tiny nothing change.
=> Bump design system to latest for question mark icon 16

app/api/util.spec.ts, app/api/util.ts, app/forms/firewall-rules-create.tsx, test/e2e/firewall-rules.e2e.ts
The diff is a nightmare compared to the amount of changes because it's a lot of shuffling and fiddly margin stuff. I'd focus on checking the rendered result.
https://console-git-firewall-rules-help-oxidecomputer.vercel.app/projects/mock-project/vpcs/mock-vpc
﻿
=> Rearrange firewall rules form and add help text

app/layouts/ProjectLayout.tsx, app/layouts/SiloLayout.tsx, app/routes.tsx, test/e2e/project-access.e2e.ts, test/e2e/silo-access.e2e.ts
Closes #2196
We do call it an IAM policy in the [API endpoint descriptions](https://github.com/oxidecomputer/omicron/blob/4fda855fc48b385ad82c667dad79f835ef7f3c76/openapi/nexus.json), but I'm not sure that changes much. It would be nice to use the word policy since that's in the endpoint's path, but Access Policy might be kind of noisy. Open to any input.
=> Rename Access & IAM to Access

app/pages/project/floating-ips/AttachFloatingIpModal.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx, mock-api/msw/db.ts
Closes #2201
Here is the bug reproduced in a test with the fix for the mock API in place but the app fix left out:
=> Don't pass project on floating IP attach from instance networking

app/pages/project/instances/instance/tabs/StorageTab.tsx, test/e2e/instance-disks.e2e.ts
Currently, we have some copy on the Storage tab of the Instance page, where we tell the user that certain conditions have to be met (the instance has to be stopped) before the user can take specific actions (detaching the disk). There's some other copy that — while technically accurate (probably) — aren't things that the user really cares about in that moment.
This PR updates that view, so that the thing the user needs to know — you need to stop the instance in order to detach the disk, or add a new disk — is more clearly linked to the next step they need to take — stopping the instance.
I'm open to copy suggestions, as always, though I think what I have here is pretty clear.
=> Update copy regarding disk attach / detach requirements

app/layouts/ProjectLayout.tsx, app/pages/SiloAccessPage.tsx, app/pages/project/access/ProjectAccessPage.tsx
Closes #2196
We had a few spots where we were using `&amp;`, so searching for `Access & IAM` didn't catch a few `Access &amp; IAM`s.
=> Access & IAM → Access – a few last spots

app/pages/project/vpcs/VpcsPage.tsx, test/e2e/vpcs.e2e.ts
Closes #2189 
The count is not really the point — the point is that it's a sneaky way to say HELLO FIREWALL RULES ARE IN HERE. The cell is a clickable link but it goes to the same thing as clicking the name.
=> Add firewall rules column to VPCs table

docs/update-pinned-api.md, tools/deno/api-diff.ts, tools/generate_api_client.sh
No functional changes. Now you don't have to clone `oxide.ts` to regen the client. `api-diff.ts` is also now standalone so I will probably move it out of this repo.
=> Use TS client generator from npm

mockServiceWorker.js, package-lock.json, package.json
The release notes mention a potential breaking change depending on whether you rely on throwing  non-response Error objects.
https://github.com/mswjs/msw/releases/tag/v2.3.0
Fortunately we already do what they say you should do, namely making sure to throw actual responses.
https://github.com/oxidecomputer/console/blob/b400ae78ac46ce7e2900607c569771accdf73e0b/app/api/__generated__/msw-handlers.ts#L1309-L1324
=> bump msw to 2.3

app/util/cli-cmd.ts
Fixes #2234
This adds slashes to the "equivalent console command" view, so copying and pasting works into a terminal works as expected.
copied output:
```
oxide instance serial console \
--project mock-project \
--instance db1
```
=> Add slashes to cliCmd for serial console

app/components/form/FullPageForm.tsx, app/forms/instance-create.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/util/links.ts
Fixes #2221 
The full-page form has a custom header, so we'll need to pass the DocsPopover component in as an optional prop.
Currently, `instance-create` is the only place where we call `FullPageForm`, so there aren't other places we need to add this in for now.
=> Add docs popover button to instance create

app/components/ErrorBoundary.tsx, app/components/ErrorPage.tsx, app/components/TopBar.tsx, mock-api/msw/handlers.ts, mock-api/msw/util.ts, test/e2e/error-pages.e2e.ts
Closes #1876 
I thought about also checking specifically for the situation where _nothing_ works, maybe by trying to hit `/session/me` and seeing if that fails, but I'd rather do that in a followup. Also the error message wouldn't be that different.
=> Add logout button to error page

app/pages/project/floating-ips/FloatingIpsPage.tsx, app/ui/lib/Tooltip.tsx, mock-api/ip-pool.ts, test/e2e/floating-ip-create.e2e.ts
Fixes #2243 
In #2242 we added the `ip_pool_id` to the response object for each Floating IP. Using the `ipPoolView` endpoint, we can pull the name of each pool, meaning we can add the IP Pool's name to the table of Floating IPs.
Hovering over the IP Pool name gives a tooltip with the description of the IP Pool, if it exists.
As there is not currently an IP Pool view at the project level (just at the system level), it doesn't make sense to set the IP Pool cell as a link (like we do with the `attached to instance` column), so we're just using a `<Badge>` component.
I made a slight tweak to the Tooltip component's prop types, as I had some confusion over why a `string` passed in as a child of the `Tooltip` wasn't working.
=> Add IP Pool to table of floating IPs

app/components/CapacityBar.tsx, app/components/TopBarPicker.tsx, app/layouts/helpers.tsx, app/pages/project/floating-ips/AttachFloatingIpModal.tsx, app/pages/project/instances/instance/SerialConsolePage.tsx, app/pages/project/instances/instance/tabs/MetricsTab.tsx, app/ui/lib/DatePicker.tsx, app/ui/lib/DateRangePicker.tsx, app/ui/lib/Pagination.tsx
In Tailwind 3.4.3, "We’ve added grow-* and shrink-* as aliases for flex-grow-* and flex-shrink-* … The old class names will always work but you’re encouraged to update to the new ones." (https://tailwindcss.com/docs/upgrade-guide#flex-grow-shrink)
We were using both `flex-grow` and `grow` (and `shrink`, and with `-0` suffixes) in the codebase already, so this just cleans it up a little.
---
Also, \* inserts Bernie gif \* I am once again asking five-minutes-ago me to remember that backticks in commit messages are a bad idea.
=> Remove flex- from grow and shrink classNames

app/components/form/fields/ImageSelectField.tsx, app/forms/access-util.tsx, app/forms/disk-create.tsx, app/forms/floating-ip-create.tsx, app/pages/project/floating-ips/AttachFloatingIpModal.tsx, app/ui/lib/Listbox.tsx
Fixes #2231 
The name `labelString` is a bit confusing. Essentially, in our Listbox components, we default to using a `label` to render the content for each item in the dropdown, and we use that same `label` to style the contents of the pseudo-input box showing the "selected" item. When the contents of the dropdown cover multiple lines, we need some alternate option to show in the "input". See the `arch-22…` line at the top, here:
We had been using a prop called `labelString`. I think it's a bit clearer to describe it as the label for the selected item, so: `selectedLabel`.
=> Move from labelString to selectedLabel

app/layouts/SystemLayout.tsx
Fixes #2173
Currently, the sidebar link directs users to `/inventory/sleds`, which means that the ReactRouter magical `isActive` prop doesn't know that it should be highlighted for either `/inventory/sleds` OR `/inventory/disks`. By changing the route to just `/inventory`, it matches for both, and so it highlights the sidebar item regardless of which tab they're on.
=> update inventory sidebar link

app/pages/project/floating-ips/FloatingIpsPage.tsx
We just added this column, and I had stuck a Badge component into the new IP Pool column. Crespo pointed out that we typically use badge elements for things like states, where the instance has one of a set of predefined options.
This PR removes the badge, leaving a regular string in its place.
But!
This does create a bit of a dilemma with the tooltip, which houses the `description` of the IP pool. @paryhin, would love your thoughts on the best path forward for this. How should we show the pool's description? I'm open to any approach that makes sense to you.
(Note that we do not have a "view IP pool" option at the project level, just at the system level, which is why this isn't a link to a "view" page.)
=> Remove Badge from IP Pool cell

app/ui/lib/CreateButton.tsx, test/e2e/instance-networking.e2e.ts
Fixes #2255
With this PR, we're adding a ternary to the CSS display logic; if the button is disabled, we use the `-disabled` color; otherwise, we use the `-secondary` color.
In this screenshot, the top button is enabled; the bottom is disabled.
=> Dim plus sign on disabled button

.eslintrc.cjs, app/components/form/SideModalForm.tsx, app/components/form/fields/DateTimeRangePicker.spec.tsx, app/components/form/fields/ListboxField.tsx, app/forms/image-upload.tsx, app/forms/vpc-edit.tsx, app/pages/SiloAccessPage.tsx, app/pages/project/access/ProjectAccessPage.tsx, app/pages/project/instances/actions.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcFirewallRulesTab.tsx, app/ui/lib/Button.tsx, app/util/file.spec.ts, app/util/math.ts, mock-api/msw/handlers.ts, mock-api/msw/util.ts, package.json, test/e2e/images.e2e.ts, test/e2e/utils.ts
I got nerd sniped by this [tweet](https://x.com/webprolific/status/1793910984664322258) and first turned on the full recommended config (which I've tried before) and it was awful:
Then I read this great blog post, which is linked in the tweet
https://www.joshuakgoldberg.com/blog/rust-based-javascript-linters-fast-but-no-typed-linting-right-now/#recap-type-checked-linting 
and it points to a couple of specific rules that it likes. So I tried turning those on and it is actually a little bit useful and doesn't slow things down that much (I also narrowed down the scope of what we're linting a bit).
=> Turn on type-aware lint rules

.eslintrc.cjs, app/components/MswBanner.tsx, app/components/RefetchIntervalPicker.tsx, app/components/form/fields/DisksTableField.tsx, app/components/form/fields/NetworkInterfaceField.tsx, app/components/form/fields/TlsCertsField.tsx, app/forms/firewall-rules-create.tsx, app/table/cells/LinkCell.tsx, app/ui/lib/ActionMenu.tsx, app/ui/lib/Button.tsx, app/ui/lib/FileInput.tsx, app/ui/lib/MiniTable.tsx, app/ui/lib/NumberInput.tsx, app/ui/lib/Pagination.tsx, app/ui/lib/RangeCalendar.tsx, app/ui/lib/Toast.tsx, app/ui/lib/Tooltip.stories.tsx, test/e2e/silos.e2e.ts
Discovered because of a delightful bug in https://github.com/oxidecomputer/console/pull/2252#issuecomment-2130334790. This actually fixes an existing bug on the instance create form where if you press enter to submit the form while in the name field, for example, it will remove an attached disk.
Closes #2260 too.
When the disk disappears, that's because I've pressed enter with a random text input focused.
https://github.com/oxidecomputer/console/assets/3612203/0d8416af-858f-45c7-9314-ba161889d792
=> Turn on react/button-has-type lint rule and fix all

app/components/form/fields/DisksTableField.tsx, app/forms/disk-attach.tsx, test/e2e/instance-create.e2e.ts, test/e2e/instance-disks.e2e.ts
Fixes #2254 
This PR filters out the already-"attached" disks from the "attach an additional disk" form that shows up during instance creation.
This is a cleaner version of what I was trying in #2257. We pass the committed disks to the form and filter them there.
=> Filter out committed disks

app/components/Terminal.tsx, app/ui/styles/index.css, package-lock.json, package.json
We missed a couple of versions due to the `@xterm/*` namespace change, and upgrading actually fixes an [issue](https://github.com/oxidecomputer/console/issues/1447#issuecomment-2155384055) where the page gets super wide for no apparently reason.
=> Upgrade `xterm`, fix super-wide serial console page

app/pages/project/instances/instance/SerialConsolePage.tsx
Closes #2273 
Solve the problem by eliminating the problem. There's a big "Back to instance" button at the top anyway.
=> Don't show instance name in serial console message

app/forms/firewall-rules-create.tsx
Fixes #2263 
Thanks @FelixMcFelix for the consultation. The host filter message is the main addition, but there are also small tweaks to the other messages.
alt="Screenshot 2024-06-26 at 4 22 52 PM">
alt="Screenshot 2024-06-26 at 4 23 01 PM">
alt="Screenshot 2024-06-26 at 4 23 05 PM">
=> More firewall rule form help copy

app/api/__generated__/msw-handlers.ts, package-lock.json, package.json
See https://github.com/oxidecomputer/oxide.ts/pull/259, which removes the ability to throw function from a handler (an antipattern) and makes zod parse errors look like regular API 400s.
=> Bump mock API generator to improve error handling

app/main.tsx, package-lock.json, package.json
See comment, I couldn't get `v7_startTransition` to work because it breaks the scroll restore test in all three browsers. The really strange thing is that I could not reproduce the issue when I did the actions manually. I suspect there's something funny about how Playwright handles `goBack` and `goForward` — it seemed like (in the tests only) the navigation state was not changing to `loading` and back, which is what we rely on to tell when to save the current scroll position before the page goes away.
https://github.com/oxidecomputer/console/blob/db99a4db4eb7f17cad953b9f4d7d804f3e1bf650/app/hooks/use-scroll-restoration.ts#L27-L37
=> RR 6.24 and turn on v7 future flags

.eslintrc.cjs, tools/deno/deploy-dogfood.ts, tools/dogfood/scp-assets.sh
Finally got tired of manually running `tools/dogfood/find-zone.sh` to confirm the gimlet numbers (which are always the same) and then running the deploy command three times or using xargs or whatever to loop over the three. This does it all in one command, with a confirmation step and without having to download the tarball three times. And it runs the three scps in parallel.
https://github.com/oxidecomputer/console/assets/3612203/c3a17e0e-2752-413d-bc2f-0c11e8604c10
=> All in one dogfood deploy script

app/components/AttachEphemeralIpModal.tsx, app/components/AttachFloatingIpModal.tsx, app/components/form/fields/ListboxField.tsx, app/components/form/fields/SubnetListbox.tsx, app/forms/floating-ip-create.tsx, app/forms/instance-create.tsx, app/forms/network-interface-create.tsx, app/forms/snapshot-create.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/system/SiloImagesPage.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, test/e2e/floating-ip-create.e2e.ts, test/e2e/images.e2e.ts, test/e2e/instance-create.e2e.ts, test/e2e/instance-networking.e2e.ts, test/e2e/ip-pools.e2e.ts, test/e2e/network-interface-create.e2e.ts, test/e2e/silos.e2e.ts, test/e2e/z-index.e2e.ts
This PR makes a few general improvements to the combobox component and a few forms that use either comboboxes or listboxes.
- All placeholders should now have a consistent phrasing — `Select a disk`, `Select a pool`, etc., rather than `Select pool`, etc.
- On the instance create form, we had been pre-filling the dropdown on the Boot Disk section with the first item in each dropdown. This made things easier for users, but removed some intentionality. We have removed the default filling of that field, meaning the user will now need to select the appropriate disk for their new instance.
- Updated tests.
=> Improve combobox implementations in preparation for v9

app/components/form/fields/SshKeysField.tsx, app/pages/ProjectsPage.tsx, app/pages/project/disks/DisksPage.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/project/images/ImagesPage.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/tabs/StorageTab.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcFirewallRulesTab.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcSubnetsTab.tsx, app/pages/project/vpcs/VpcsPage.tsx, app/pages/settings/SSHKeysPage.tsx, app/pages/system/SiloImagesPage.tsx, app/pages/system/networking/IpPoolsPage.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/pages/system/silos/SilosPage.tsx, app/ui/lib/EmptyMessage.stories.tsx, app/ui/lib/EmptyMessage.tsx
Fixes #2289 
It was quick to update the copy here, though if we decide we want to remove the text completely, that's fine, too. I think for now it makes sense to keep the text in place.
I added a `text-balance` CSS class to balance multi-line text, though I'm holding lightly to that if we aren't into it:
**Without `text-balance`:**
**With `text-balance`:**
=> Update empty state text

app/pages/project/instances/instance/InstancePage.tsx
Closes #2276 
Fixing them is too complicated and doesn't seem worth it. Bye!
=> Remove cmd+k quick actions from instance detail page

app/pages/project/images/ImagesPage.tsx
This makes the Project Images page header consistent with the Silo Images page header
Fixes #2309
=> Update header on Project Images page to say "Project Images"

app/forms/image-edit.tsx
Currently, the Image "edit" form title defaults to saying "Edit {silo|project} image", which is confusing, as it isn't actually editable. This PR just updates that to make it less confusing. The URL is not changed; presumably we will be able to edit aspects of Images in time.
=> Update image 'edit' form title, as form isn't actually editable

app/forms/silo-create.tsx, app/ui/lib/Message.tsx
Was going to make an issue, but why not just do it.
=> Add docs link to silo create form, "SAML JIT" -> "SAML"

.github/workflows/lintBuildTest.yml, package.json
Hide punycode deprecation warnings and remove min/max threads from test command in CI. The latter were added 2 1/2 years ago in https://github.com/oxidecomputer/console/pull/654. Seems to work fine without it!
=> chore: tweak test commands

app/components/Sidebar.tsx, app/ui/lib/Button.tsx, app/ui/lib/Message.tsx, app/ui/lib/TipIcon.tsx, app/ui/lib/Toast.tsx, tailwind.config.js
Closes #2268. I also cleaned up a couple of other variants.
I wasn't able to find any spots where we were relying on the bad setup, but we should give it a bit more testing.
=> Fix `disabled:` Tailwind variant

app/components/TopBarPicker.tsx
This removes the truncation in the topbar dropdown, just in case that's the direction we want to go with it. If not, no worries.
Fixes #2327 if we go with it.
=> Remove truncation on topbar dropdown

.eslintrc.cjs, app/components/StatusBadge.tsx, app/pages/system/inventory/DisksTab.tsx, app/pages/system/inventory/SledsTab.tsx, mock-api/sled.ts, test/e2e/inventory.e2e.ts
This PR adds columns for the Policy and State on the Sleds tab, as we have them on the Disks tab.
The columns on the right side are new:
Same as before:
Fixes #2333
=> Add columns on SledsTab for sled Policy and State

app/forms/firewall-rules-create.tsx, app/forms/firewall-rules-edit.tsx, app/forms/firewall-rules-util.ts
HMR does not like it when the same file exports both React components and other stuff. When you do that, you get a full page reload on changes instead of a hot reload, plus this message:
Moving the function out of the file containing the form fixes this.
=> tooling: Fix HMR on firewall rules form

app/ui/lib/Modal.tsx
We fixed this once in #1714, though maybe it was only for side modals. In any case, here I swap the order in the HTML so the confirm button autofocuses and use `flex-row-reverse` to get them to display visually in the right order. This has the downside that tabbing through goes in a funny order, but that seems less bad on net than the status quo.
=> Focus confirm button instead of cancel in modals

app/forms/image-upload.tsx, app/ui/lib/Modal.tsx, app/ui/lib/SideModal.tsx, app/ui/lib/modal-context.ts, app/util/all-zeros.spec.ts, app/util/str.ts
It doesn't like non-components and components exported from the same file.
=> tooling: fix two more spots where vite complains it can't HMR

mock-api/msw/handlers.ts, mock-api/msw/util.ts, mock-api/util.ts, mock-api/vpc.ts, test/e2e/firewall-rules.e2e.ts, test/e2e/networking.e2e.ts, test/e2e/vpcs.e2e.ts
* Remove `allow-rdp` rule, which was removed in the real API a long time ago
* Set up the default rules in new VPCs that get created
* Update VPC create form test to actually submit the form
=> tooling: make mock API default firewall rules more accurate

app/components/form/fields/NameField.tsx, app/forms/firewall-rules-create.tsx, app/forms/firewall-rules-edit.tsx, test/e2e/firewall-rules.e2e.ts
Closes #2220 
Still needs a little work, maybe copy polish and more importantly putting an error indicator at form level so there's some feedback if you hit submit while the name field is off screen.
=> Error on firewall rule name conflicts

app/components/form/SideModalForm.tsx, app/ui/lib/SideModal.tsx, test/e2e/silos.e2e.ts
Learned about `shouldFocus: true` while reading the docs to understand #2364. Trivial improvement. It's even tested.
https://github.com/user-attachments/assets/19009f20-9de2-4a95-9d44-410a737a6f35
https://github.com/user-attachments/assets/5df55e4b-23f6-498a-9f7d-12a44a11e7ca
=> Focus name field on API name already exists error

app/components/form/fields/ListboxField.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/ui/lib/Listbox.tsx
Closes #2345 
RHF automatically focuses the first field with an error, but we were not passing the `ref` for the image select listbox through to the button. And it must be the button specifically because the wrapping divs are not focusable unless they have a tabindex.
https://github.com/user-attachments/assets/cebc763c-fdfd-416d-bd4c-f0ec69501986
=> instance create: focus image field on validation error

app/pages/settings/SSHKeysPage.tsx, app/util/links.ts
Fixes #2211 
Am 100% open to revamping this copy.
=> Add docs popover for SSH Keys

app/components/TopBar.tsx, app/ui/lib/DropdownMenu.tsx, app/ui/styles/components/menu-button.css
Closes #2342 
Looks like this works, but I need to make sure there's nothing weird about it. I had noticed this problem before, but for some reason when I saw #2342 I immediately had a vision of how to do it.
```[tasklist]
```
=> Use real links in dropdown menus

app/forms/vpc-router-route/shared.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcRoutersTab.tsx
This PR adds a warning to the router deletion confirmation box, noting that routes under that router will also be deleted.
Also, as system routers should not be delete-able ([see here](https://github.com/oxidecomputer/omicron/blob/914f5fd7d51f9b060dcc0382a30b607e25df49b2/nexus/src/app/vpc_router.rs#L136-L138)), this PR also updates the UI to disable that option:
=> Refactor Router deletion process

app/pages/project/instances/instance/SerialConsolePage.tsx, mock-api/msw/handlers.ts, test/e2e/instance-serial.e2e.ts, test/e2e/instance.e2e.ts, test/e2e/utils.ts
Closes https://github.com/oxidecomputer/console/issues/2326
So beautiful 😢. I pulled this out of #2360 because it seems to me uncontroversially very good and ready to merge as-is.
https://github.com/user-attachments/assets/d37e1034-129b-4633-a500-fcf3f4cf69c2
=> Connect to serial console of starting instance

app/pages/project/vpcs/VpcPage/tabs/VpcRoutersTab.tsx
This just tightens up a table row that had been double-height:
=> make routers table row shorter

mock-api/vpc.ts
This reverts the default system router route's destination values to `0.0.0.0/0` (IPv4) and `::/0` (6).
=> Update system router's route IP values

app/components/TimeAgo.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/system/inventory/sled/SledInstancesTab.tsx, app/table/cells/InstanceStatusCell.tsx, mock-api/instance.ts, test/e2e/instance.e2e.ts
Closes #2357
We were giving `hostname` way too much prominence considering it's not really doing anything.
=> Instances table: remove hostname, normal row height, split CPU/RAM

app/api/util.ts, app/pages/project/instances/instance/tabs/StorageTab.tsx, mock-api/msw/handlers.ts
=> Update links to API code about hard-coded allowed transitions

app/components/TopBarPicker.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/InstancePage.tsx
Closes #2380
We'll want to revisit the overall breadcrumb designs (see #2380 for a few possible directions / links to more in Figma), but in the interim, we can add the dropdown to the instance item in the breadcrumb nav.
=> Add dropdown to instance breadcrumb

app/pages/project/vpcs/VpcPage/tabs/VpcSubnetsTab.tsx, app/table/cells/RouterLinkCell.tsx
=> Don't include parent selector in fetch by ID

app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/InstancePage.tsx, app/ui/lib/Table.tsx, app/util/array.spec.tsx, app/util/array.ts, test/e2e/instance.e2e.ts, test/e2e/utils.ts
Closes #2377 
When the page loads below, it polls every 3 seconds because there is an instance in a starting state. After 30 seconds, it would switch to polling every minute, but I don't wait for that in this clip. I stop the instance, which causes it to transition to `stopping`, and the `stopped` (because of the polling). At that point, there are no instances in transitional states, so polling slows to every minute (i.e., not at all in the short time in this clip). Then when I start the instance it polls again while it's in `starting` and then stops (slows) again after it's `running`.
https://github.com/user-attachments/assets/3328ec0f-ceef-4b93-bad1-77d5b1eb5d05
=> Polling on instance list

app/components/StateBadge.tsx, app/pages/project/disks/DisksPage.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/instance/InstancePage.tsx, app/pages/project/instances/instance/SerialConsolePage.tsx, app/pages/project/instances/instance/tabs/StorageTab.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/system/inventory/sled/SledInstancesTab.tsx, app/table/cells/InstanceStateCell.tsx, test/e2e/disks.e2e.ts, test/e2e/instance.e2e.ts, test/e2e/utils.ts
No good reason to call these columns "status" when they're called "state" in the API.
=> Rename "status" columns to more correct "state"

mock-api/msw/db.ts, mock-api/msw/handlers.ts
Trying to avoid the bug fixed in https://github.com/oxidecomputer/console/pull/2394, where we accidentally include parent selectors. At first I thought we should figure out how to do this automatically, hence https://github.com/oxidecomputer/oxide.ts/issues/264, but as noted there, it's hard to do automatically, and I remembered we already have this whole manually-implemented mock DB lookup apparatus in the console. We have run into this category of bug once before, and I fixed it in precisely this way in https://github.com/oxidecomputer/console/pull/2203, but only for one resource, which is silly.
The mechanical stuff here was pretty easy. The annoying part was going through the real API and code fixing a couple of spots where we currently deviate.
=> Mock API: error if parent selectors present when resource is fetched by ID

app/forms/ip-pool-edit.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/networking/IpPoolsPage.tsx, app/routes.tsx, test/e2e/ip-pools.e2e.ts
This PR moves the "Edit IP pool" side modal from the IP Pools list page to the individual IP Pool view page. In some ways, this makes more sense with our existing URL schema, as the edit URL is `http://localhost:4000/system/networking/ip-pools/:pool/edit`, so is conceptually already a child of the pool itself, rather than the list.
We start with an additional actions button in the header …
… which leads to the side modal on the view page …
The `delete` button is disabled for IP Pools with existing ranges …
… but is enabled for IP Pools that can, in fact, be deleted:
Closes #2353, and if we feel this is a good pattern to replicate, we can roll it out to other resources as well.
=> Move IP Pools edit form to view page

app/pages/system/UtilizationPage.tsx
The silo names on the /utilization page should be a link to the silo page. 
(the whole table cell is the link, despite the pink rectangle only being on the name)
=> Link silo view page from utilization page

app/forms/ip-pool-edit.tsx
Followup for https://github.com/oxidecomputer/console/pull/2405#discussion_r1739475703, which I posted seconds after merge. I made the conditional narrower and added a comment.
=> Tweak IP pool edit `onSuccess` logic

app/pages/system/UtilizationPage.tsx, app/table/columns/action-col.tsx, test/e2e/images.e2e.ts, test/e2e/utilization.e2e.ts
This adds a column to the `system/utilization` page, allowing users to copy the ID of the silo on each row. As this table is constructed a bit differently than our other tables where we pass the columns in, I extracted some existing code into a RowActions component that we can call independently (as we do in this PR). The new component also has an optional prop for `copyIdLabel`, in case we want to use more specific copy than "Copy ID" (as we do in this PR).
Closes #2344
Minor sidenote: We had an existing "did it copy to the clipboard?" test that was skipping for Safari and Firefox. It's still uncooperative for CI contexts, but Firefox is now working, [as of June 2024,](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#browser_compatibility) so we aren't skipping that …
=> Add table row action to copy silo ID from system utilization page

app/forms/image-upload.tsx, test/e2e/image-upload.e2e.ts
Test flakes pretty much always look like this. The assert about them all being ready is sort of ill-conceived anyway.
=> tools: try to reduce flake in image upload e2e tests

app/pages/ProjectsPage.tsx, app/pages/SiloAccessPage.tsx, app/pages/project/access/ProjectAccessPage.tsx, app/pages/project/disks/DisksPage.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/project/images/ImagesPage.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/project/vpcs/RouterPage.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcFirewallRulesTab.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcRoutersTab.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcSubnetsTab.tsx, app/pages/project/vpcs/VpcsPage.tsx, app/pages/settings/SSHKeysPage.tsx, app/pages/system/SiloImagesPage.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/networking/IpPoolsPage.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/pages/system/silos/SilosPage.tsx
This PR migrates a couple of files over from using the raw object returned by `useApiMutation` to using the `mutateAsync` function from within that object. Partially addresses #2367, though there will be more to migrate in time.
=> Use renamed functions in place of raw useApiMutation object

app/pages/project/vpcs/VpcsPage.tsx
We were missing a toast to confirm when a VPC was successfully deleted.
=> Add missing 'VPC deleted' toast

app/forms/firewall-rules-create.tsx
We sort by `priority` for display purposes in the table, but there's no need to sort for the form PUT.
=> minor: don't need to sort firewall rules for create form

app/ui/lib/Truncate.tsx, mock-api/vpc.ts
In the draft v10 release notes, description was cut off in my routes screenshot, but I was pretending I didn't notice. @benjaminleonard, however, could not so pretend. He said it was "bad." Touché.
So I thought, let's try using CSS's built in truncation on top of ours. The only reason we do that to begin with is so we can detect when we're truncating and add a tooltip on hover showing the full text. But combining the two works shockingly well. The reason it's a draft is I want to go and look at all the places we call `Truncate` and make sure they look good.
https://github.com/user-attachments/assets/bbdcd452-5009-452d-9819-ecf9614fdc20
=> Truncate truncated descriptions even more

.git-blame-ignore-revs
By adding this file with a0c29a535d17b0f57fa5fa9bee7cca05631885fc and a8fcdab9e906f8ff37bb106c20e8364f371c9997, uninteresting refactors are left out of the blame. I did this before in #1972 but the commit in question included something I didn't want to exclude. This feature adds some pressure to do totally mechanical refactors in their own PR so they can be excluded from the blame without excluding anything interesting. Inspired by https://github.com/oxidecomputer/omicron/pull/6461.
=> Start `.git-blame-ignore-revs`

app/api/util.ts, test/e2e/instance.e2e.ts
Closes #2438. I might add a test, though.
https://github.com/user-attachments/assets/0f8c61d2-da56-4295-abc0-5117ef4afdf8
=> Allow user to start failed instances

test/e2e/image-upload.e2e.ts
Followup to #2415. Flakes seem less frequent but we still [saw one](https://github.com/oxidecomputer/console/actions/runs/10820606878/job/30021009761).
=> minor: tweak image upload cancel e2e for less flake

app/forms/image-upload.tsx, mock-api/msw/handlers.ts, test/e2e/image-upload.e2e.ts, test/e2e/utils.ts
We might be upsetting Safari in the GH actions VM by allocating too many 15 MB files.
=> Reduce mock file size in image upload tests

playwright.config.ts, test/e2e/image-upload.e2e.ts, test/e2e/silos.e2e.ts, test/e2e/utils.ts
=> chore: skip image upload e2es in safari

app/forms/vpc-router-route-common.tsx, app/forms/vpc-router-route-create.tsx, app/forms/vpc-router-route-edit.tsx, app/pages/project/vpcs/RouterPage.tsx, app/pages/project/vpcs/VpcPage/tabs/VpcRoutersTab.tsx
There was a lot of duplicated code in the VPC router route create/edit forms. I started on #2388, but realized it'd be good to clean the forms up a little first, so this is the result of that refactoring. Open to other refinements, if anything stands out.
=> Extract common fields and refactor VPC router route forms

app/pages/project/disks/DisksPage.tsx
I believe this is the last migration needed to close out #2367. I scanned through looking at all instances of `= useApiMutation` to see if their variables were A) not destructured and B) used in a dependency array, and this was the only one that I saw that still needed to be switched over.
=> Use destructured mutate method for dependency array

app/pages/project/instances/instance/tabs/StorageTab.tsx
Groundwork for #2453 to make the diff there tiny. No behavior should change here. This table will never paginate because the list is capped at 8 items, so there's no need for `QueryTable`. This also has the advantage of removing the extraneous pagination UI control from the bottom of the page.
=> refactor: don't use `QueryTable` for instance disks table

app/ui/lib/ActionMenu.tsx, app/ui/lib/use-stepped-scroll.ts
Just a small thing I noticed while checking our few uses of `eslint-disable-next-line react-hooks/exhaustive-deps` because of [this tweet](https://x.com/mjackson/status/1836277438550282546). [`createRef`](https://react.dev/reference/react/createRef) is not really a thing anymore — it's for class components. Refs created with `useRef` are referentially stable and fine to use in the dep array.
=> minor: change incorrect `createRef` to `useRef`

app/pages/project/instances/instance/tabs/StorageTab.tsx
I don't like this very much but we might be stuck with it. The make actions callback depending on the instance state means it gets remade when the instance state changes, which means the whole table gets nuked when the instance goes from stopping to stopped, causing the row actions menu to be closed.
https://github.com/user-attachments/assets/5ecf8f2b-3d8e-4f02-9843-c7c0eb77d1e8
=> Fix instance disk row menu closing on instance state change

app/components/Pagination.tsx, app/layouts/helpers.tsx, app/table/QueryTable.tsx, app/ui/lib/Pagination.tsx, test/e2e/snapshots.e2e.ts
While looking at #2457 I could not find a place where `inline` pagination is actually used. It's also all wonky, with some components defaulting to `inline` and some components defaulting to `page`. Will comment inline because there's some weirdness, but the goal here is to change nothing about any actually existing usages.
=> cleanup: Remove "inline" pagination

app/pages/project/instances/instance/tabs/NetworkingTab.tsx
Same deal as #2453. Diff is much better [with whitespace hidden](https://github.com/oxidecomputer/console/pull/2460/files?diff=split&w=1) since there's a big indent involved.
https://github.com/user-attachments/assets/9b5cee04-70ce-4a9e-987e-f3835efaca01
=> Fix row actions on instance NICs table closing when polling

app/api/window.ts, app/components/AttachEphemeralIpModal.tsx, app/forms/disk-attach.tsx, app/forms/firewall-rules-common.tsx, app/forms/firewall-rules-create.tsx, app/forms/firewall-rules-edit.tsx, app/forms/floating-ip-create.tsx, app/forms/instance-create.tsx, app/forms/snapshot-create.tsx, app/pages/project/floating-ips/FloatingIpsPage.tsx, app/pages/project/instances/instance/tabs/NetworkingTab.tsx, app/pages/system/networking/IpPoolPage.tsx, app/pages/system/silos/SiloIpPoolsTab.tsx, app/util/consts.ts
Extract the constant used in `limit: 1000` — our shorthand for "approximately everything" — into a new exported const, `APPROXIMATELY_EVERYTHING`.
Closes #2459
=> Extract const for APPROXIMATELY_EVERYTHING

app/util/consts.ts
Should've entered this as a doc comment instead of two slashes.
=> Switch from double-slash to doc comment, for better help at callsites

app/forms/firewall-rules-common.tsx, app/ui/lib/Combobox.tsx
When initially making the Combobox component, I'd used the `isDisabled` prop name to hint at the boolean type it was expecting. I realized, when refactoring code for https://github.com/oxidecomputer/console/pull/2448/files, that it'd be more convenient if it matched other field types, and was simply `disabled`. This PR switches it over.
=> Update isDisabled prop name for Comboboxes

app/api/hooks.ts, app/forms/vpc-router-route-common.tsx, app/forms/vpc-router-route-create.tsx, app/forms/vpc-router-route-edit.tsx, app/routes.tsx, test/e2e/vpcs.e2e.ts
This PR converts the text fields in the VPC Router Routes form to be — when appropriate — prepopulated dropdowns.
For Destinations, that's when the Destination Type has been selected as `Subnet`; for Targets, `Instance`s.
Closes #2388
=> Add dropdowns to router route form for destinations and targets

app/forms/instance-create.tsx, test/e2e/instance-create.e2e.ts
This swaps the boot disk selector for existing images from a Listbox to a Combobox. The two components expect the same props, so this is actually really easy. This is part of #1837.
This also now moves from the one-off `DISK_FETCH_LIMIT` to `ALL_ISH`, both being equivalent to 1,000.
We'll have a more involved change to handle the image selector change (also for #1837), since we'll be moving from basic strings in the dropdown to using ReactNodes, so I'll pull all of that into a different PR.
=> Migrate disk selector in instance-create to Combobox

app/api/util.ts, test/e2e/instance.e2e.ts
Closes #2468 
As of https://github.com/oxidecomputer/omicron/pull/6652, failed instances can be stopped. This PR reflects that in the UI, and adds a test for it.
See https://github.com/oxidecomputer/omicron/blob/f0b804818b898bebdb317ac2b000618944c02457/nexus/src/app/instance.rs#L818-L830 for more
=> Allow user to stop failed instances

app/components/form/fields/ComboboxField.tsx, app/forms/firewall-rules-common.tsx, app/forms/ip-pool-range-add.tsx, app/forms/network-interface-edit.tsx, app/forms/vpc-router-route-common.tsx, app/util/ip.spec.ts, app/util/ip.ts, app/util/str.spec.ts, app/util/str.ts, mock-api/msw/handlers.ts, mock-api/msw/util.ts, test/e2e/firewall-rules.e2e.ts, test/e2e/instance-networking.e2e.ts, test/e2e/vpcs.e2e.ts
Followup work for https://github.com/oxidecomputer/console/pull/2437#issuecomment-2362290469
- ~~Confirm Rust code has the same validation results (https://github.com/oxidecomputer/test-ip-validation)~~
=> Validate IPs and IP networks

mock-api/msw/handlers.ts
Noticed while working on #2464. 
As the comment says: because we don't bother with being "smart" or "correct" in the mock API, we don't have sagas or transactions that let us undo DB writes when we run into an error in a complex handler like instance create. Instead, we have to make sure we do as much validation as we can up front so we can be Moderately Confident the DB writing portion of the operation is going to work if we manage to get that far. The floating IPs code combined validation and DB writes, which meant we could attach one IP and then blow up on the next one, leaving the first IP attached even though instance create overall failed. This change moves the validation earlier so we can blow up before any DB writes have happened.
=> mock API: Move floating IP checks earlier in instance create handler

app/pages/project/instances/actions.tsx, app/stores/confirm-delete.tsx
It might be nice to give these a slightly different visual treatment, like a top box, but it would also be noisy. This is a slight improvement on the status quo, so I'm going for it.
=> Give extra line in confirm modals its own paragraph

app/pages/project/floating-ips/FloatingIpsPage.tsx, app/table/cells/IpPoolCell.tsx, app/ui/lib/Tooltip.tsx
We'll likely be using the IpPoolCell in the new Network Gateways page; this extracts it out to its own component.
We were already following the "fetch the list and then seed the ReactQuery cache with relevant data" approach, so this is really just moving the component around.
=> Extract IpPoolCell so we can use it in other places

app/components/TopBarPicker.tsx, app/layouts/SystemLayout.tsx
Closes #1527 
This adds a sled picker to the topbar on the Sled view page
=> Add picker to Sled page topbar

app/ui/lib/Listbox.tsx, test/e2e/floating-ip-create.e2e.ts, test/e2e/instance-create.e2e.ts, test/e2e/instance-networking.e2e.ts
Closes #2417 
This does two things. One, it gets rid of the strange empty `id` that had been in the Listbox elements. (We had already fixed Comboboxes in #2474.)
This also better links the Label and Listbox element, so when you click on the label, the focus goes to the Listbox.
=> Fix listbox IDs; better link labels to inputs

app/components/ErrorBoundary.tsx
This adds a bit of error logging to the browser dev tools.
This was in #2488, but isn't directly related to that work, and since that PR needs some more thinking / general work, I figured I'd pluck it out of that branch.
=> Add console.error to the error boundary

app/pages/project/floating-ips/FloatingIpsPage.tsx
Closes #2500
This makes the IP addresses on the Floating IPs list page copyable.
=> Make IP on Floating IPs page copyable

app/components/DocsPopover.tsx, app/components/form/fields/DisksTableField.tsx, app/ui/styles/components/mini-table.css
Closes #2486 
Closes #2490 
This adds a truncation component to the name cell, to prevent it from breaking the layout when the disk has a long name.
**Broken:**
**Fixed:**
=> Add truncation component to prevent table breakage

app/api/util.spec.ts, app/api/util.ts
I noticed while working on #2361 that `instanceCan` allows any string as a key, which means you can do `instanceCan.detaaaaaach(instance)` and not get a type error. The goal here was to make that a type error without affecting the API, so we don't have to change any call sites. ~~After some back and forth with myself around several ways one could make this work, I landed on this, which is more verbose than I prefer, but it's fine.~~ I did it.
Rather than try to explain the other stuff I tried, here is a fun and exciting video of me suffering.
https://github.com/user-attachments/assets/c289c8eb-f090-42ec-824e-3892d43d66e2
=> minor: refactor `instanceCan` and `diskCan` for better type safety

app/forms/image-upload.tsx
Closes #2270
Reduce `gcTime` on upload chunk React Query mutation from default of 5 minutes to zero.
As I say in the comment, I don't even understand why the mutation cache exists — it's not like we're reading from it. The query cache is a different story. So I don't see a downside to turning it off for this mutation. I have asked about in the Tanstack Discord and on Twitter, so I'll see if anything helpful comes out of that.
https://tanstack.com/query/v5/docs/reference/MutationCache
https://tanstack.com/query/v5/docs/framework/react/reference/useMutation
https://tkdodo.eu/blog/mastering-mutations-in-react-query
Taking some snapshots in FF throughout a big upload. Memory goes up and up.
Memory fluctuates around a relatively small value, consistent with GC functioning as desired.
As a …
=> How about we don't hold the entire image in memory

app/components/form/fields/NameField.tsx, app/components/form/fields/TextField.tsx, app/forms/network-interface-create.tsx, test/e2e/project-create.e2e.ts
Users are prevented — when submitting a create form — from using spaces, uppercase letters, or anything besides `[a-z0-9-]` in their `Name` fields.
This PR moves that restriction to the actual `NameField` itself, so when a user types in a space, it's entered in as a dash, when they enter an uppercase letter, it's added as a lowercase letter, and when they enter any non-allowed character, nothing is added to the field.
=> Add realtime typing restrictions on NameField

app/forms/idp/create.tsx, app/forms/idp/edit.tsx, app/ui/lib/TextInput.tsx, mock-api/silo.ts, test/e2e/silos.e2e.ts
This field was already present, just hidden in the "edit" (though not really editable) view.
I also adjusted the help text's CSS to have `text-balance`, so we avoid having ragged descriptions.
Closes #2473
=> Add Group Attribute Name field to IdP view

app/components/TopBar.tsx, app/components/TopBarPicker.tsx, app/ui/styles/components/menu-button.css, tailwind.config.js
Per #2521, action menu dropdowns were stacking behind the footer bar, which has a z-index of `20`. 
This PR updates the imported classes for `.DropdownMenuContent` to use a z-index of `25`. We also had a few overrides of the default z-index in TopBar and TopBarPicker, but since those are now using the same z-index, we can remove the overrides.
I have clicked through as many scenarios as I can think of regarding popovers and modals, and all seem to be working as expected.
Closes #2521.
=> Fix dropdown z index

app/components/DocsPopover.tsx, app/pages/project/instances/InstancesPage.tsx, app/pages/project/instances/actions.tsx, app/pages/project/instances/instance/InstancePage.tsx, app/table/columns/action-col.tsx, app/ui/lib/Button.tsx, app/ui/lib/Tooltip.tsx, test/e2e/instance.e2e.ts, test/e2e/utils.ts
> I plan to be fussy about it
— David Crespo
Partially fixes #2419 (just the instance detail page)
=> Instance action buttons

app/components/form/fields/ip-pool-item.tsx
I tried using https://typescript-eslint.io/rules/strict-boolean-expressions to catch this, but even with the following config I got 78 errors. It gets thrown off by types that are a union including `null` or `undefined` — doesn't seem to understand that they're nullable.
```js
'@typescript-eslint/strict-boolean-expressions': [
'error',
{
allowNumber: false,
allowNullableNumber: false,
allowString: true,
allowNullableObject: true,
allowNullableEnum: true,
allowNullableBoolean: true,
allowNullableString: true,
allowAny: true,
},
],
```
=> Fix rendering of empty IP pool description

app/components/form/fields/NameField.tsx
This 1Password thing on `name` fields in our forms is so silly.
I've noticed this forever but didn't realize how easy it would be to fix. 
https://www.stefanjudis.com/snippets/turn-off-password-managers/
=> Tell password managers to stop trying to fill `name` field

app/forms/firewall-rules-common.tsx, app/ui/lib/SideModal.tsx
https://console-git-side-modal-title-oxidecomputer.vercel.app/projects/mock-project/vpcs/mock-vpc/firewall-rules-new
---
Added `SideModal.Heading` – example usage on Firewall Rules side modal to be used also within #2511.
The size looks good to me, making it semi seems to have made the difference in distinguishing it.
Also in terms of usage – I think a heading should always be preceded by a divider, things are going to get messy if we drop it in to group inputs willy nilly.
=> Add side modal heading

app/ui/lib/SideModal.stories.tsx, app/ui/lib/SideModal.tsx
In local dev, Radix was giving a spurious error and a technically true but pointless warning on our side modal. This PR gets rid of both.
=> Fix radix warnings on side modal

app/components/form/SideModalForm.tsx, app/forms/disk-attach.tsx, app/forms/idp/edit.tsx, app/forms/image-edit.tsx, app/forms/image-from-snapshot.tsx, app/forms/network-interface-create.tsx, app/forms/snapshot-create.tsx
Thanks @taspelund for the report.
https://github.com/user-attachments/assets/6eea9cde-1eb3-409f-b28c-ffc60cfcc89e
=> Require loading prop on `SideModalForm`, fix snapshot create

app/forms/idp/create.tsx, app/ui/lib/Message.tsx, test/e2e/silos.e2e.ts
Following up on https://github.com/oxidecomputer/console/pull/2511#issuecomment-2460418920. Let's be sooooooo helpful.
=> Add help text + request signing section header to IdP form

app/ui/lib/TextInput.tsx
In Safari, input fields currently suggest spellchecked variations of what you've entered:
This PR turns that off:
Note, though, that there are some browser-level preferences that we do not have control over, like this one:
which decides to suggest names from your contacts list to the "Name" field:
I looked into various ways of turning that off, but everything I found was hacky (like adding hidden pseudo form fields to the page to intercept autocompletes, [as described in this SO thread](https://stackoverflow.com/questions/22661977/disabling-safari-autofill-on-usernames-and-passwords)).
Nevertheless, field-level spellchecking prefs do seem to be respected by the browser, so we'll apply that here.
Closes #2532
=> Disable spellcheck on inputs

app/forms/firewall-rules-common.tsx, app/forms/network-interface-edit.tsx, app/ui/lib/MiniTable.tsx, test/e2e/firewall-rules.e2e.ts
We already had the logic in place to disable the `clear` button in the subform, we just hadn't applied it to the submit button. This PR applies the same prop logic to both the `clear` and the `add` button — you can't take either action if there's no value in the subform; if the value is there, you can take either action.
Closes #2547
=> Disallow firewall-rule subform submission when target / host filter value is missing

app/components/form/fields/NameField.tsx, app/ui/lib/Combobox.tsx, app/util/str.spec.tsx, app/util/str.ts
We are already restricting some of the characters that users can add to the Name field. While working on #2546 I figured that it might be helpful to have this string manipulation available in an external function, so we can restrict what's typed in to the Combobox field. Because we'll want to give users the option of typing a number in as the initial character ("I'm trying to filter for Images with `2024` in them"), the `nameSyntax` function has an optional second prop. Left off, the default action is to only permit a letter in the zeroth position. If `true` is passed in to `allowNonLetterStart`, the user can enter either a number or a dash. Non-allowed characters are dropped.
=> Set up normalizeName string utility function

app/forms/instance-create.tsx, test/e2e/instance-create.e2e.ts
This update changes how the fallback boot disk name is generated. Currently, we use the ID of the image used as the boot disk, but we'd like to use the image's name instead. The user is still able to set a boot disk name, as normal.
We are also looking into a means of showing the image used as the boot disk so that info is available whether the user names their boot disk or not, but that's a separate issue from this one.
Closes #2476
=> Generate boot disk name from image name

app/ui/lib/MiniTable.tsx, package-lock.json, package.json, tailwind.config.js
Was just testing https://github.com/oxidecomputer/design-system/pull/82 — might as well PR now that it works. Will merge once that is merged and we can use a non-canary version. No effect on bundle size — guess tree-shaking was already working for us.
=> chore: Use ESM version of design system (no functional changes)

package-lock.json, package.json, playwright.config.ts
Playwright 1.49 has an interesting new Chrome version that upgrades the way they do headless mode so that it's more authentic Chrome, but potentially slightly slower. It could have breaking changes, but it works fine for me locally and didn't seem slower either. I also wanted to upgrade for a new Safari version since we've been seeing some Safari flake lately.
https://github.com/microsoft/playwright/releases/tag/v1.49.0
=> chore: bump playwright to 1.49

app/ui/lib/DatePicker.tsx, app/ui/lib/DateRangePicker.tsx
Woof. We recently made comboboxes / listboxes larger, to match the height of input fields. The DatePicker component had an independent height, though, and so it wasn't matching the height of the listbox on the Metrics page. This fixes that, so DatePickers now match the other input components' heights.
Broken:
Fixed:
=> Set date pickers to match other input elements' heights

test/e2e/z-index.e2e.ts
I added this test in #1747, @charliepark's epic PR from before he started. In #2522 we specifically changed it so that the dropdowns are on top of the topbar. I'm not really clear on why this test continues to pass, but also flakes. It suggests it's a bad test. So I am fine deleting it.
=> minor: Delete inapplicable z-index e2e test

app/api/client.ts, app/api/hooks.ts
tiny bit of cleanup, uninteresting
=> cleanup: inline `getUseApiQueryClient`

app/api/hooks.ts, test/e2e/breadcrumbs.e2e.ts
Was inspired. 
https://x.com/TkDodo/status/1857764199813861829
The goal here is to keep this change very minimal and show that nothing changes in order to enable a more interesting followup change improving `QueryTable`. But it makes some other interesting things possible (which I don't do in this PR):
```ts
export const apiq = getApiQueryOptions(api.methods)
```
```diff
- apiQueryClient.prefetchQuery('projectList', { query: { limit: PAGE_SIZE } })
- useApiQuery('projectList', { query: { limit: PAGE_SIZE } })
+ const projectListOptions = apiq('projectList', { query: { limit: PAGE_SIZE } })
+ 
+ queryClient.prefetchQuery(projectListOptions)
+ useQuery(projectListOptions)
```
See also tRPC’s [RFC](https://github.com/trpc/trpc/discussions/6240) to do something very similar in their generated …
=> refactor: Use `queryOptions` API to clean up `useApiQuery` hook definitions

app/api/client.ts, app/api/hooks.ts, app/api/util.ts, app/layouts/helpers.tsx, app/pages/project/snapshots/SnapshotsPage.tsx, app/pages/system/inventory/DisksTab.tsx, app/pages/system/inventory/SledsTab.tsx, app/table/QueryTable.tsx, app/table/QueryTable2.tsx, app/ui/lib/Pagination.tsx, mock-api/snapshot.ts, test/e2e/pagination.e2e.ts, test/e2e/scroll-restore.e2e.ts, test/e2e/snapshots.e2e.ts, test/e2e/utils.ts
This is built on top of the `queryOptions` work in #2566. The types in `QueryTable` have always bothered me, as does returning a component instead of an element, but I could never figure out how to fix it.
https://github.com/oxidecomputer/console/blob/0f922b2ed3af596beae37adaae4ecff545002ed0/app/table/QueryTable.tsx#L65-L77
This change:
* Fixes the types so we don't use `any`
* Uses a much more intuitive mechanism to enforce that we can only use QueryTable with list endpoints (simply require `TData extends { items: TItem[] }`)
* Returns the React Query query result containing the data, so in cases where we are currently making a second `useApiQuery` call where we painstaking ensure the params match (see below), we don't have to do that anymore
* Keeps previous page around while loading …
=> refactor: new `useQueryTable` with legit types, returns the query data

app/api/client.ts, app/api/hooks.ts, app/api/index.ts, app/api/util.ts
Followup to 
* #2567 
* #2571 
* #2575
=> cleanup: delete unused API helper things

app/pages/project/instances/instance/InstancePage.tsx, app/ui/lib/Modal.tsx, test/e2e/utils.ts
Closes #2585 
`Modal.Footer` has more lines of props than lines of code. Not my favorite.
=> Make pressing enter submit instance resize modal form

app/pages/project/instances/actions.tsx, test/e2e/instance-serial.e2e.ts
Removed in #2487, back by popular demand. Went with second from bottom because when Delete is enabled, it looks weird for it not to be at the bottom. Note that even though this is a simple link, it doesn't let you middle click — we need #1855, which I put in milestone 13. It's easy, might even get it into v12.
=> Put back serial console in instance actions

test/e2e/instance-create.e2e.ts
Reordering things so we're less likely to miss the `creating` state in this common flake scenario.
=> Try to make instance create e2e less flaky

mock-api/msw/handlers.ts, test/e2e/instance-serial.e2e.ts
Trying to improve this flake.
```
Error: Timed out 5000ms waiting for expect(locator).toBeVisible()
Locator: getByText('Waiting for the instance to start')
Expected: visible
Received: <element(s) not found>
Call log:
- expect.toBeVisible with timeout 5000ms
- waiting for getByText('Waiting for the instance to start')
25 |   // the instance is running. skip the check for "creating" because it can
26 |   // go by quickly
> 27 |   await expect(page.getByText('Waiting for the instance to start')).toBeVisible()
|                                                                     ^
28 |   await expect(page.getByText('The instance is starting')).toBeVisible()
29 |   await expect(page.getByText('The instance is')).toBeHidden()
30 |
at /Users/runner/work/console/console/test/e2e/instance-serial.e2 …
```
=> minor: Lengthen instance creating state so e2es are less likely to miss it

package-lock.json, package.json, tailwind.config.ts
Our janky old JS file gets rejected by [Node.js v22.12](https://github.com/nodejs/node/releases/tag/v22.12.0), which in theory is supposed to make `require` work _better_, but we're probably doing something ugly. Fortunately we have no need to use `require`.
=> chore: Convert tailwind config to typescript file

app/ui/lib/Modal.tsx
Fixed the `DialogTitle` error, which, I was dismayed to see, is not suppressed in production. Maybe for good reason, because it got me to fix it.
Note that the accessible title was actually _not_ broken in production — the problem here is that we were hooking up the title ID to the dialog ourselves rather than letting Radix dialog handle it, so it thought we weren't doing it.
=> minor: hook up `Dialog.Title` better in modal to fix Radix errors

app/api/hooks.ts
Passing React Query's abort signal into our API `fetch` calls means the calls get aborted when queries get canceled due to being unmounted. One inconvenient time for this to happen is when React [Strict Mode](https://react.dev/reference/react/StrictMode) does its thing in dev mode, causing an unmount and remount in the middle of a prefetch in a loader, which doesn't itself blow up because `prefetchQuery` eats errors, but components that expect prefetched data do blow up because the prefetch failed to populate the query cache. There isn't much advantage to canceling queries, so we can fix this by just not passing the signal through.
With #2597 we started using an options helper with `prefetchQuery` that passes the abort `signal` from React Query through into our API calls, which means they …
=> Fix e2e flake by not consuming abort signal in `apiq` query options helper

app/pages/project/instances/instance/tabs/StorageTab.tsx, test/e2e/instance-disks.e2e.ts, test/e2e/instance.e2e.ts
We've broken this several times by accident, so this time I added a test. Very straightforward.
=> Fix instance disk menus closing on poll

app/pages/project/instances/instance/tabs/StorageTab.tsx, test/e2e/instance-disks.e2e.ts
This PR adds a confirmation modal when detaching a disk from an instance.
Closes #2613
=> Add confirmation modal for disk detachment

app/pages/project/vpcs/internet-gateway-edit.tsx, test/e2e/vpcs.e2e.ts
Less jarring to link to the router than to an open form. Also makes it easier to get back with keyboard shortcuts because they're not eaten by the form.
=> Gateway route links to router instead of route edit form

app/ui/lib/Badge.tsx
I find it a little dim.
I think it makes #2624 look better too, that's why I thought of it.
=> Lighten solid neutral badge bg

app/pages/system/UtilizationPage.tsx, app/pages/system/inventory/SledsTab.tsx, app/table/Table.tsx, mock-api/sled.ts, test/e2e/instance-create.e2e.ts, test/e2e/inventory.e2e.ts, test/e2e/utils.ts
Closes #2623 
We don't have a great pattern for values like this, but I think it's tolerable. All possible combinations for the policy column are pictured.
=> Display full sled policy in table

app/table/cells/InstanceLinkCell.tsx, test/e2e/disks.e2e.ts
This was something I noticed when working on #2630, but figured I'd handle separately, as it isn't relevant to that PR.
This PR just modifies the InstanceLinkCell component to use an EmptyCell when appropriate.
Here's the before:
Here's the after:
=> Use EmptyCell when we'd have an empty cell in InstanceLinkCell

app/ui/lib/ActionMenu.tsx, test/e2e/action-menu.e2e.ts, test/e2e/silos.e2e.ts
This adds an `event.preventDefault()` to the Action Menu when the user hits the enter key. This prevents the event from bubbling up and accidentally submitting the form prematurely.
Closes #2584
=> Prevent the sidemodal form from immediately erroring when using the action menu

.eslintrc.cjs, test/e2e/instance-disks.e2e.ts, test/e2e/instance.e2e.ts
See https://github.com/oxidecomputer/console/pull/2618#issuecomment-2539806844
I was able to get each test to fail by sticking something in a dep array that didn't belong there.
=> Full tests for row actions menu polling bug

app/components/TimeSeriesChart.tsx
Before:
After:
Applying the border and border to the area chart directly was causing issues.
=> Fixes padding bug on chart

app/pages/project/vpcs/internet-gateway-edit.tsx
This PR adds an ID field to the Internet Gateway details view.
Closes #2656
=> Add ID row to Internet Gateway side modal

app/ui/styles/components/mini-table.css
A slight tweak to the CSS on mini-table cells. Previously, we highlighted the entire mini-table row on hover, but we really just want to highlight the div containing the button in the last cell.
With the fix in place, when hovering the mouse over the top row's last cell (though the mouse is removed from the screenshot):
Closes #2662
=> Fix minitable hover css

app/forms/image-upload.tsx, mock-api/msw/handlers.ts, test/e2e/image-upload.e2e.ts
Trying to fix some flakes that came up in #2671 (and periodically for a very long time). I think we were calling cleanup twice more often than I thought.
=> Improve image upload cleanup logic, reduce e2e flake

app/components/ErrorBoundary.tsx, app/forms/image-upload.tsx, app/pages/ProjectsPage.tsx, app/ui/lib/Message.tsx, app/util/links.ts, mock-api/msw/handlers.ts, test/e2e/error-pages.e2e.ts, test/e2e/image-upload.e2e.ts, test/e2e/utils.ts
Closes #2573 
Obviously the copy could be shorter, but in theory this error should only show up to operators immediately after IdP setup and virtually never again.
Doc link goes to: https://docs.oxide.computer/guides/operator/faq#_how_do_i_fix_the_something_went_wrong_error, which is added in [v13](https://github.com/oxidecomputer/docs/pull/513), so it won't work until that's merged.
=> Better error for admin group name misconfig

test/e2e/image-upload.e2e.ts
Trying to do #2687 
The fact that the failure was due to the step still being `ready` when it was expecting `running` makes me think the upload step is taking _slightly_ too long, and we're running out of time waiting for the step after it.
=> minor: longer timeout on image upload cancel state expect

app/api/__generated__/util.ts, mock-api/disk.ts, package-lock.json, package.json
=> Upgrade TS client gen for date parsing fix

app/components/form/fields/ImageSelectField.tsx, app/forms/disk-create.tsx, app/forms/instance-create.tsx, app/util/math.spec.ts, app/util/math.ts, mock-api/snapshot.ts, test/e2e/disks.e2e.ts, test/e2e/pagination.e2e.ts, test/e2e/snapshots.e2e.ts
Closes #2640 
We set the disk size to the size of the selected snapshot or image, rounded up to the nearest 10, but we were not clamping it to make sure it was at most 1023. The input element refuses to set a value above the max, so it shows 1023, but the form state in memory (which is what gets validated and what gets sent to the API) keeps the bad value. I guess I should add a test.
=> Fix size validation on disk create from 1023 GiB snapshot

app/components/CopyCode.tsx, app/components/form/FullPageForm.tsx, app/components/form/SideModalForm.tsx, app/pages/project/instances/instance/SerialConsolePage.tsx, app/pages/project/instances/instance/tabs/ConnectTab.tsx, app/ui/lib/Modal.tsx
Taking some noise out of #2654 
Same except now the width is on auto with a min of 24rem (same width as narrow)
=> minor: Abstract equivalent command modal into `CopyCode`

app/components/CopyCode.tsx, app/pages/project/instances/instance/tabs/MetricsTab/OxqlMetric.tsx, app/util/links.ts
Adding for parity with the Figma designs:
---
Splits the copy code modal and the button so that the modal can be called without a regular button.
It might be simpler to just remove the button part completely. Will defer to you guys.
The docs link thing is placeholder. There's two potential improvements that probably should be made.
1. We adapt the actions menu to take links (both internal and external` that use the `Dropdown.LinkItem`. This has the benefit of making the other links in these menus openable with a command click
2. The way we link to docs is potentially brittle. Want some way of validating that these sections do in fact exist. But a hash docs link won't 404.
=> Metrics more actions

app/components/TimeSeriesChart.tsx
Seems like a small change but it makes them feel much more resolved in the container.
Comments explain it pretty well, but essentially we can figure out the container width by taking the width of a character – which we know – and adding the padding and tick stroke size. Recharts does not have a way of doing this natively.
It is possible to calculate the width of a string, given the string and the text using the canvas – which is dynamic of course but probably overkill in this instance. We might need to re-evaluate for mobile layouts eventually.
Before:
After:
=> Dynamic chart Y axis width

playwright.config.ts, test/e2e/firewall-rules.e2e.ts, test/e2e/utils.ts
This is about #2704.
Not going to close it yet because I'm not sure this really fixed it.
=> Fix firefox test flake on firewall rule targets

app/components/form/fields/RadioField.tsx, app/table/QueryTable.tsx, app/ui/lib/AuthCodeInput.tsx, app/ui/lib/DialogOverlay.tsx, app/ui/lib/DropdownMenu.tsx, app/ui/lib/FileInput.tsx, app/ui/lib/NumberInput.tsx, app/ui/lib/SideModal.tsx, app/ui/lib/TextInput.tsx, app/util/classed.ts
The diff is about 1/10 as long with [whitespace hidden](https://github.com/oxidecomputer/console/pull/2715/files?w=1).
=> chore: get rid of `forwardRef` thanks to React 19

app/pages/project/instances/CpuMetricsTab.tsx, app/pages/project/instances/DiskMetricsTab.tsx, app/pages/project/instances/InstancePage.tsx, app/pages/project/instances/NetworkMetricsTab.tsx, app/routes.tsx, app/util/__snapshots__/path-builder.spec.ts.snap, app/util/path-builder.spec.ts, app/util/path-builder.ts
I think having the crumb at the top change when you change tabs feels excessive. I also removed plain `/metrics` as a path in path-builder and had the tab link straight to the CPU tab. This eliminates a loader call that could cause the loading bar to flash twice.
=> minor: Remove breadcrumbs for instance metrics tabs

test/e2e/instance-create.e2e.ts
See #2694.
Will close that in a bit if we stop seeing the flake.
=> tools: Fix safari instance additional disks e2e flake

app/components/CopyIdItem.tsx, app/components/MoreActionsMenu.tsx, app/components/TopBar.tsx, app/components/oxql-metrics/OxqlMetric.tsx, app/pages/project/instances/InstancePage.tsx, app/pages/project/instances/actions.tsx, app/pages/project/vpcs/RouterPage.tsx, app/pages/project/vpcs/VpcPage.tsx, app/pages/project/vpcs/VpcSubnetsTab.tsx, app/pages/system/networking/IpPoolPage.tsx, app/table/columns/action-col.tsx, app/ui/lib/DropdownMenu.tsx, app/ui/styles/components/loading-bar.css, app/ui/styles/components/menu-button.css, tsconfig.json
Closes #1855 
Closes #2174
It's more noisy than it needs to be because I also cleaned up some duplicated logic that didn't need to exist — notice there are net deletes despite the increase in functionality. I think I would like to convert `RowActions` to taking elements directly as children as well instead of using these action config objects we have to memoize, but that would be too much churn for this PR: we have row actions in like 20 files.
=> Allow links in row actions and more actions dropdowns

app/components/MswBanner.tsx, app/components/PageSkeleton.tsx, app/routes.tsx, tailwind.config.ts
Figured out how to do it and it is good. Closes #1569. In the video a show that we avoid showing the skeleton on login and device token verify pages that do not have the grid lines.
https://github.com/user-attachments/assets/a6d427d3-92b5-447f-a8c4-c52494d07b32
=> Page loading skeleton

app/layouts/SystemLayout.tsx, app/pages/system/inventory/InventoryPage.tsx
This was added in #1341, when it was actually used to display metadata about the rack on the page. We removed that display but didn't remove the fetch.
=> trivial: don't do unnecessary racks fetch on inventory page

app/components/RefetchIntervalPicker.tsx, app/pages/SiloUtilizationPage.tsx, app/pages/project/instances/MetricsTab.tsx, app/pages/system/UtilizationPage.tsx
Making more consistent with other chart layouts. Also means we can simplify the interval picker.
=> Tighten spacing and more consistent with other layouts

app/components/RefetchIntervalPicker.tsx, app/components/SystemMetric.tsx, app/components/TimeSeriesChart.tsx, app/components/oxql-metrics/OxqlMetric.tsx, app/pages/SiloUtilizationPage.tsx, app/pages/project/instances/MetricsTab.tsx, app/pages/system/UtilizationPage.tsx
Looking at #2732, #2733, and #2737, I realized we'd benefit from simplifying the chart component, and one source of complexity was the fact that the non-OxQL system and silo utilization charts were styled differently. So here I bring them up to date with the new style and eliminate the props we were using to differentiate.
=> Convert old charts to new style

app/forms/instance-create.tsx
=> Fix tooltip spacing on instance create

app/pages/project/affinity/AffinityPage.tsx, app/pages/project/affinity/AntiAffinityGroupPage.tsx, mock-api/msw/handlers.ts
This PR handles the deleting of affinity groups and the removal of affinity group members. Creation / editing flows will add a good bit more as we add modals to handle those operations, so I'm inclined to keep this one scoped to just the delete actions.
=> Delete affinity groups / remove affinity group members

app/components/oxql-metrics/OxqlMetric.tsx, app/pages/project/instances/MetricsTab.tsx, mock-api/msw/handlers.ts, test/e2e/instance-metrics.e2e.ts
We missed this in #2654. We didn't notice it on dogfood because we don't test the console regularly enough with non-fleet viewer users.
Closes #2774
=> Make OxQL instance metrics work for non-fleet viewer users

app/components/form/fields/DateTimeRangePicker.tsx, app/ui/lib/CalendarCell.tsx, app/ui/lib/DateRangePicker.tsx
=> Move error into picker

app/api/util.ts, app/pages/project/instances/AntiAffinityCard.tsx, test/e2e/anti-affinity.e2e.ts
This sets it so the user can't add the instance to an anti-affinity group when the instance is not stopped.
=> Prevent adding instance to A-A group when not stopped

app/api/util.ts, app/forms/anti-affinity-group-member-add.tsx, app/pages/project/affinity/AntiAffinityGroupPage.tsx, app/pages/project/instances/AntiAffinityCard.tsx, app/pages/project/instances/NetworkingTab.tsx, app/pages/project/instances/SettingsTab.tsx, app/table/columns/action-col.tsx, test/e2e/anti-affinity.e2e.ts
Closes #2771 
Feels a little
maybe needs one fewer "anti-affinity".
=> Affinity group add/remove on instance settings tab

app/forms/instance-create.tsx, app/pages/project/access/ProjectAccessPage.tsx, app/pages/project/instances/NetworkingTab.tsx, app/pages/system/networking/IpPoolPage.tsx
=> minor: remove periods from tooltip messages

app/api/hooks.ts, app/api/index.ts, mock-api/snapshot.ts, test/e2e/pagination.e2e.ts, test/e2e/snapshots.e2e.ts
This should substantially reduce the proportion of the time that going past the first page is required. None of our JSON responses are that big, the API is fast, and it's probably rare for people to have that many of most resources. If everything is on one page, then ctrl-f works for find and it's less of a problem that we don't have filtering yet.
I'd also like to make the tables more dense by reducing vertical space, but this doesn't require that at all.
=> Increase list page size to 50

app/forms/idp/shared.tsx, app/pages/project/instances/AutoRestartCard.tsx, app/ui/lib/FieldLabel.tsx
This adds the `text-raise` class to the FieldLabel component, which is used for many/most of the input labels.
Turns this …
to this …
Closes #2787, I believe, but Ben let me know if I misunderstood that.
=> Add text-raise class to FieldLabels

app/components/form/fields/DateTimeRangePicker.tsx, package-lock.json, package.json
I noticed on dogfood it's too easy to overload OxQL by holding the up arrow in the time picker. Input wasn't debounced, so we were firing a request for every value of the input. I couldn't believe how easy this was to do. 400ms seems quite responsive while fully solving the problem.
https://github.com/user-attachments/assets/0c045c78-466d-4426-a7da-a4e60e9da88b
https://github.com/user-attachments/assets/05f1bfcf-ef54-48a2-b05d-98c5b81b050b
=> Debounce `startTime` and `endTime` in date range picker

app/components/DocsPopover.tsx, test/e2e/docs-popover.e2e.ts, test/e2e/images.e2e.ts
It occurred to me it would be nice to get a tooltip on the docs popover button on hover. Instead of saying "Links to docs" I made it use the same title we had in the popover.
=> minor: fix label and title on docs popover button

app/components/IpPoolUtilization.tsx, app/pages/system/networking/IpPoolsPage.tsx, app/ui/lib/DateTime.tsx, app/ui/lib/Table.tsx
Easter present for @david-crespo. Slightly thinner column cells. I tried `h-10` but that was a bridge too far.
In contrast the taller rows could do with a design pass. In some places at least these could be converted to smaller rows.
=> Thinner small rows

app/components/DocsPopover.tsx, app/components/MoreActionsMenu.tsx, app/components/TopBar.tsx, app/ui/lib/Button.tsx, app/ui/lib/CopyToClipboard.tsx, app/ui/styles/components/button.css
How does this ~~3~~ 38 line CSS PR somehow add sound effects to all the buttons? Beats me.
=> Surf it, scroll it, pause it, click it

app/pages/project/instances/NetworkingTab.tsx, test/e2e/instance-networking.e2e.ts, test/e2e/instance.e2e.ts, test/e2e/utils.ts
This adds an affordance to the instance networking tab, to prevent the deletion of a primary NIC when there are other NICs present.
As called out in #2652, we prevent the user from deleting the primary NIC when there are other NICs present. As Ben notes,
>There is always zero or one primary NIC. There may zero or more secondary NICs (up to 7 today), but only if there is already a primary. The primary NIC is where we attach all the external networking state, like external addresses, and the VPC information like routes, subnet information, internet gateways, etc.
>
>You may delete any secondary NIC. You may delete the primary NIC only if it's the only NIC (there are no secondary NICs). That's because we need a place to attach that external state -- if you delete a primary, we can only make …
=> Disable primary NIC delete when multiple NICs present

app/pages/project/instances/AntiAffinityCard.tsx
Charlie and I spent some time on this after noticing pretty frequent failure locally — guess it was just a coincidence that it worked in recent PRs and main commits. We were not memoizing the columns of the affinity groups table on the instance settings tab, so any render (caused, e.g., by instance state polling) would reset an open row actions menu. Related to #2618 and #1091.
=> Fix affinity test flake due to missing column memoization

.oxlintrc.json, app/forms/instance-create.tsx, app/ui/lib/Radio.tsx, app/ui/styles/components/form.css
One small thing, one small but open for discussion.
1. Tighten divider spacing, side modal and full page form are now the same
2. Removing the highest preset, if the user wants these values they can do so in the custom tab and this wraps awkwardly
=> Full page form spacing

test/e2e/instance-create.e2e.ts
Got a test flake on main that I don't think I've seen before. The trace shows it failing to click on this combobox behind the bottom bar.
Scrolling puts it right in the middle, so I expect it will help.
```
Retry #2 ───────────────────────────────────────────────────────────────────────────────────────
Test timeout of 60000ms exceeded.
Error: locator.click: Test timeout of 60000ms exceeded.
Call log:
- waiting for getByRole('option', { name: 'arch-2022-06-01' })
- locator resolved to <div role="option" tabindex="-1" data-focus="" data-active="" aria-selected="false" data-headlessui-state="active focus" id="headlessui-combobox-option-«r2i»" class="relative border-b border-secondary last:border-0">…</div>
- attempting click action
2 × waiting for element to be visible, enabled and stable
- …
```
=> Test flake: scroll image combobox into view

app/api/__generated__/Api.ts, app/api/__generated__/validate.ts, app/api/hooks.ts, app/components/InstanceAutoRestartPopover.tsx, app/components/form/fields/useItemsList.ts, app/components/oxql-metrics/util.spec.ts, app/forms/network-interface-create.tsx, app/forms/subnet-create.tsx, app/forms/subnet-edit.tsx, app/forms/vpc-router-route-common.tsx, app/pages/system/silos/SiloQuotasTab.tsx, app/table/cells/InstanceLinkCell.tsx, app/table/cells/RouterLinkCell.tsx, app/ui/lib/Pagination.tsx, mock-api/instance.ts, mock-api/msw/db.ts, mock-api/msw/handlers.ts, mock-api/msw/util.ts, package-lock.json, package.json
Closes #2820 
Note that while there are many lines of changes to the generated types and zod validators (the latter only used in the mock API), the only runtime app change is the change from `undefined` to `P.nullish` in the offending `match` in the auto restart popover.
=> Regen API client with proper nullable fields

app/forms/instance-create.tsx
On the instance-create table, there's a checkbox that has a gap between the checkbox and the label, mostly because we were re-creating something that already works. This update uses the default checkbox / label approach, making it work like other places in the app.
It is possible I have missed something, so will poke around a bit more to see if there are more broken checkbox/labels.
Fixes #2807
=> Fix target for checkbox on instance create form

app/api/util.ts, app/forms/instance-create.tsx, app/pages/project/instances/InstancePage.tsx, mock-api/msw/handlers.ts, test/e2e/instance-create.e2e.ts
Closes #2824 
Turns out we don't have any tests exercising these limits, and while testing it I noticed that we do something really annoying on instance create if you type in too big of a RAM amount. Unlike in the resize modal, where we correctly show an error on blur, on instance create we just silently change the value to the max.
=> Bump max instance RAM to 1024 GiB

app/components/form/fields/DisksTableField.tsx, app/forms/disk-attach.tsx, app/forms/instance-create.tsx, test/e2e/instance-create.e2e.ts
This adds in a fix for #1662, where we aren't showing the size of the _attached_ disks in the disks minitable.
As this isn't necessary for the `data-minitable` branch, I'm happy to wait until that branch is merged and I can merge this to main, but if you want to include it in the branch, it's available.
Closes #1662.
=> Show size of attached disks in mini table

mock-api/json-type.ts, package-lock.json, package.json, tsconfig.json, vite.config.ts
https://vite.dev/blog/announcing-vite7
Next step is trying out [`rolldown-vite`](https://github.com/vitejs/rolldown-vite), which is very close to ready.
Draft because I'm seeing test failures locally.
=> Vite 7 + friends

app/pages/system/inventory/SledsTab.tsx, app/pages/system/inventory/sled/SledBadges.tsx, app/pages/system/inventory/sled/SledPage.tsx
This PR adds policy data (already present on the sleds overview page) to the individual sled view page.
Before:
After:
This does lose the `Location | Coming soon` line, but I suspect that was added as a means of balancing the rows.
It also adjusts the order of cells in a way that makes more sense on a larger window (like having the two "Usable _____" cells in the bottom of the right-hand column), but as most of our layouts are optimized for desktops over mobile, this seemed like it made more sense.
Closes #2837
=> Add sled policy data to sled page

app/api/util.ts, test/e2e/instance-create.e2e.ts
Since https://github.com/oxidecomputer/omicron/pull/8527 the control plane has been happy to accept such sizes.
=> Bump max instance RAM to 1536 GiB

app/api/client.ts, app/api/hooks.ts, app/hooks/use-current-user.ts, app/pages/project/snapshots/SnapshotsPage.tsx, app/table/cells/IpPoolCell.tsx
Because there are only a few uses of `useApiQueryErrorsAllowed`, it's trivial to convert them all to the new preferred format that lets use vanilla `useQuery`.
Note this leaves in place `apiQueryClient.prefetchQueryErrorsAllowed`, which is only used in one spot, but I don't feel like figuring out how to reconcile the slight difference in logic right now.
https://github.com/oxidecomputer/console/blob/777a95998530f93e17276c1f4ffcd33bd9bbb955/app/api/hooks.ts#L320-L335
=> Add errors-allowed version of `apiq` and use it everywhere
