app/pages/system/UtilizationPage.tsx
app/test/e2e/utilization.e2e.ts
libs/util/math.spec.ts
libs/util/math.ts

Update how our util functions round numbers

---

app/components/TopBarPicker.tsx
app/pages/ProjectsPage.tsx
app/pages/project/disks/DisksPage.tsx
app/pages/project/images/ImagesPage.tsx
app/pages/project/instances/InstancesPage.tsx
app/pages/project/instances/instance/tabs/NetworkingTab.tsx
app/pages/project/instances/instance/tabs/StorageTab.tsx
app/pages/project/networking/VpcsPage.tsx
app/pages/project/snapshots/SnapshotsPage.tsx
app/pages/settings/SSHKeysPage.tsx
app/pages/system/SiloImagesPage.tsx
app/pages/system/SiloPage.tsx
app/pages/system/SilosPage.tsx
app/pages/system/inventory/DisksTab.tsx
app/pages/system/inventory/InventoryPage.tsx
app/pages/system/inventory/RacksTab.tsx
app/pages/system/inventory/SledsTab.tsx
app/pages/system/inventory/sled/SledInstancesTab.tsx
app/test/e2e/click-everything.e2e.ts
app/test/e2e/disk-create.e2e.ts
app/test/e2e/instance/disks.e2e.ts
app/test/e2e/pagination.e2e.ts
app/test/e2e/snapshots.e2e.ts
libs/api-mocks/snapshot.ts
libs/table/QueryTable.tsx

Open to other suggestions for the number here (maybe 24 if this feels like too big of a jump) – don't want to go too high because then we need to worry about scroll restoration and it defeats the point of paginating to begin with.
Somewhat fixes #1794

Increase pagination size from 10 to 25

---

libs/ui/lib/listbox/Listbox.tsx
libs/ui/lib/side-modal/SideModal.tsx
libs/ui/lib/tooltip/Tooltip.tsx
libs/ui/lib/tooltip/tooltip.css

Was testing a tooltip and noticed it wasn't appearing within a side modal – carried over the dynamic z-index from the listbox.

Use dynamic z-index for tooltips too

---

app/pages/system/networking/IpPoolsTab.tsx

Add IP pools to quick actions

---

app/pages/project/instances/instance/tabs/NetworkingTab.tsx
test/e2e/instance-create.e2e.ts
test/e2e/instance/networking.e2e.ts

Closes #1986 
https://console-3vxp9j7p3-oxidecomputer.vercel.app/projects/mock-project/instances/db1/network-interfaces

Move primary NIC badge into name column

---

app/util/math.spec.ts
app/util/math.ts

Fix rounding bug on `n >= 1000` 

---

app/components/RouteTabs.tsx
app/forms/firewall-rules-create.tsx
app/ui/lib/ActionMenu.tsx
app/ui/lib/AuthCodeInput.tsx
app/ui/util/keys.ts

We had this `KEYS` object in our ui/utils folder, but weren't using it consistently. This PR just uses it in a few more places.

Clean up KEYS imports

---

playwright.config.ts
test/e2e/ip-pools.e2e.ts

Will only merge if any of it appears to work.

Reduce e2e flake

---

app/pages/project/instances/instance/tabs/StorageTab.tsx

This should fix a failing test, due to case inconsistencies.

simplify column header; fix failing test

---

app/components/TopBarPicker.tsx
app/pages/ProjectsPage.tsx
app/pages/project/disks/DisksPage.tsx
app/pages/project/floating-ips/FloatingIpsPage.tsx
app/pages/project/images/ImagesPage.tsx
app/pages/project/instances/InstancesPage.tsx
app/pages/project/instances/instance/tabs/StorageTab.tsx
app/pages/project/snapshots/SnapshotsPage.tsx
app/pages/project/vpcs/VpcPage/VpcPage.tsx
app/pages/project/vpcs/VpcsPage.tsx
app/pages/settings/SSHKeysPage.tsx
app/pages/system/SiloImagesPage.tsx
app/pages/system/inventory/DisksTab.tsx
app/pages/system/inventory/InventoryPage.tsx
app/pages/system/inventory/SledsTab.tsx
app/pages/system/inventory/sled/SledInstancesTab.tsx
app/pages/system/networking/IpPoolPage.tsx
app/pages/system/networking/IpPoolsPage.tsx
app/pages/system/silos/SiloPage.tsx
app/pages/system/silos/SilosPage.tsx
app/table/QueryTable.tsx

Seems obvious in hindsight! Now we can increase the page size instantly if we feel like it after #2158.

Import `PAGE_SIZE` constant from QueryTable for all list prefetches

---

app/components/CapacityBars.tsx
app/forms/silo-create.tsx

Closes #2195
Was thinking about saying something like "count" but I think this is straightforward enough.

nCPUs -> vCPUs

---

app/components/DocsPopover.tsx
app/components/ErrorPage.tsx

Size spacing nits

---

app/pages/SiloUtilizationPage.tsx
test/e2e/utilization.e2e.ts
test/e2e/z-index.e2e.ts

We had already done this for system utilization. Good catch @paryhin.

Take capacity out of silo utilization page title

---

.github/workflows/license-check.yml
.github/workflows/reformatter.yaml
.github/workflows/upload-assets.yaml

Bump deprecated GH actions

---

app/pages/project/vpcs/RouterPage.tsx

Urf. This is an improvement, but open to further edits.

Update copy in docs popup

---

app/table/cells/EnabledCell.tsx

Update roundel in EnabledCell for disabled badge

---

app/pages/ProjectsPage.tsx
app/ui/lib/EmptyMessage.tsx

Thought of this while listening to a podcast about UI design. The system works!

More helpful empty projects table text

---

app/components/form/Form.tsx

Closes #2403 
Let's just do the dumbest thing.
https://github.com/user-attachments/assets/1aa5154e-9b0c-49b9-acb1-bf865c14d9a0

Move full page form error next to the buttons on wide windows

---

package.json

This was useful on another PR, but wasn't directly related, so pulling it into its own.
Open to editing the script if there are any modifications, but this seemed fast and easy.

Add script to enable npm run update-snapshots

---

package-lock.json
package.json

I thought we might have dependencies complain but I only had to bump like two other things.

chore: Upgrade to Vite 6

---

package-lock.json
package.json

It just works. Cuts some noise out of our lockfile. Boring.

chore: use vitest 3.0 beta (it uses vite 6)

---

package-lock.json
package.json

chore: bump headless to 2.2

---

app/ui/lib/Checkbox.tsx

Fix indeterminate border and hover state

---

app/pages/system/UtilizationPage.tsx

Closes #2677 
The alternative would be to paginate, but that is annoying, plus it doesn't cover the metrics silo listbox — that still has to fetch all.

Fetch all-ish silos on utilization page

---

app/ui/styles/components/loading-bar.css

Realized the loading bar motion could be annoying when I myself got annoyed at it. Here is an attempt at a pulsing version for `prefers-reduced-motion` that is still a little in-your-face but at least it doesn't move. Kinda nice! [Diff with indentation changes hidden](https://github.com/oxidecomputer/console/pull/2720/files?w=1) is better.
https://github.com/user-attachments/assets/d3dd4966-da3c-4df9-a4e0-2dfccca3eb6f

Reduced motion loading bar

---

package-lock.json
package.json

Affinity icon for upcoming affinity/anti-affinity page.

Update DS for affinity icon

---

app/pages/project/instances/CpuMetricsTab.tsx
app/pages/project/instances/DiskMetricsTab.tsx
app/pages/project/instances/NetworkMetricsTab.tsx

Closes #2714. See notes in that issue about CPU states. Confirmed in Q&A channel that none of my choices here are egregious.

Descriptions for CPU metrics

---

app/ui/lib/Combobox.tsx

Fix button bg color on disabled combobox

---

app/pages/SiloAccessPage.tsx
app/pages/project/access/ProjectAccessPage.tsx
app/util/__snapshots__/path-builder.spec.ts.snap

Closes #2777 
Small net improvement IMO.

Give silo and project access pages better titles

---

app/pages/project/instances/AntiAffinityCard.tsx
app/pages/project/instances/InstancePage.tsx
app/pages/project/instances/SettingsTab.tsx
app/util/links.ts

I'm making the corresponding change to the docs URL in the docs PR.

minor: update affinity docs link, cut a few lines

---

app/forms/anti-affinity-group-member-add.tsx
app/pages/project/instances/AntiAffinityCard.tsx

Closes https://github.com/oxidecomputer/console/issues/2794

minor: toasts for errors on affinity group member add

---

package-lock.json
package.json

Closes dependabot PRs all at once.

Bump vite, vitest, react-router, design-system

---

app/components/form/fields/DateTimeRangePicker.tsx

Fix date picker re-renders by breaking debounce loop
